<a href="https://colab.research.google.com/github/eildes06/Assigments/blob/main/DAwPython_Capstone_(AutoScout)_Project_Studentanalaysispart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

# WELCOME!

## Introduction
Welcome to "***AutoScout Data Analysis Project***". This is the capstone project of ***Data Analysis*** Module. **Auto Scout** data which using for this project, scraped from the on-line car trading company in 2019, contains many features of 9 different car models. In this project, you will have the opportunity to apply many commonly used algorithms for Data Cleaning and Exploratory Data Analysis by using many Python libraries such as Numpy, Pandas, Matplotlib, Seaborn, Scipy you will analyze clean dataset.

The project consists of 3 parts:
* First part is related with 'data cleaning'. It deals with Incorrect Headers, Incorrect Format, Anomalies, Dropping useless columns.
* Second part is related with 'filling data'. It deals with Missing Values. Categorical to numeric transformation is done.
* Third part is related with 'handling outliers of data' via Visualisation libraries. Some insights are extracted.

# PART- 1 `( Data Cleaning )`

In [9]:
import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
from pylab import rcParams
sns.set_style("darkgrid")
import plotly
import plotly.express as px
import plotly.graph_objs as go
import plotly.offline as py
from plotly.offline import iplot
from plotly.subplots import make_subplots
import plotly.figure_factory as ff
import warnings
warnings.filterwarnings("ignore")

In [10]:
scout_car = pd.read_json ('/content/scout_car.json', lines = True)
df = scout_car.copy()
df.sample(3)

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,...,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
15456,https://www.autoscout24.com//offers/renault-es...,Renault Espace,V Espace Initiale Paris Dci 160 Edc 7places + ...,None,33400,None,886 km,08/2018,None,NaN,...,[\nCette voiture sera facturée 27 833 euros HT...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
13814,https://www.autoscout24.com//offers/renault-cl...,Renault Clio,dCi 8V 90CV EDC Start,Sedans,14900,Price negotiable,"19,900 km",10/2016,None,NaN,...,[\nVendesi clio my2017 restyling in condizioni...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
6986,https://www.autoscout24.com//offers/opel-astra...,Opel Astra,1.4 Turbo S&S Excellence (125 CV),Compact,11955,None,"39,754 km",03/2017,None,NaN,...,"[\n, 6930JXT, Oferta de financiación, consulta...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.sample(3).T

,1914,2524,5784
url,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/opel-astra...
make_model,Audi A1,Audi A1,Opel Astra
short_description,Sportback 30 TFSI 85(116) kW(PS) S tronic,Sportback 30 TFSI APS DAB SHZ GRA AMI MMI-Radio,K Sports Tourer Edition 2PDC|ANDROID|136PS
body_type,Compact,Compact,Station wagon
price,28755,22490,15790
vat,VAT deductible,None,VAT deductible
km,- km,10 km,"18,423 km"
registration,-/-,06/2019,12/2017
prev_owner,None,None,1 previous owner
kW,NaN,NaN,NaN
hp,85 kW,85 kW,100 kW
Type,"[, New, , Super 95]","[, Employee's car, , Super 95]","[, Used, , Diesel (Particulate Filter)]"
Previous Owners,NaN,NaN,\n1\n
Next Inspection,NaN,NaN,"[\n12/2020\n, \n119 g CO2/km (comb)\n]"
Inspection new,NaN,\nYes\n,NaN
Warranty,NaN,"[\n, \n, \n116 g CO2/km (comb)\n]","[\n6 months\n, \nEuro 6\n]"
Full Service,NaN,"[\n, \n, \nEuro 6d-TEMP\n]",NaN
Non-smoking Vehicle,NaN,"[\n, \n, \n4 (Green)\n]","[\n, \n, \n4 (Green)\n]"
null,[],[],[]
Make,\nAudi\n,\nAudi\n,\nOpel\n
Model,"[\n, A1, \n]","[\n, A1, \n]","[\n, Astra, \n]"
Offer Number,[\nGSB337-Q2\n],[\n2837\n],[\nIAC-169\n]
First Registration,NaN,"[\n, 2019, \n]","[\n, 2017, \n]"
Body Color,"[\n, Blue, \n]","[\n, White, \n]","[\n, Grey, \n]"
Paint Type,[\nMetallic\n],NaN,[\nMetallic\n]
Body Color Original,[\nFirmamentblau\n],[\nCortinaweiss\n],[\nQuarz Grau\n]
Upholstery,"[\nCloth, Black\n]","[\nCloth, Black\n]","[\nCloth, Black\n]"
Body,"[\n, Compact, \n]","[\n, Compact, \n]","[\n, Station wagon, \n]"
Nr. of Doors,[\n5\n],[\n5\n],[\n4\n]
Nr. of Seats,NaN,[\n5\n],[\n5\n]
Model Code,[\n0588/BNO\n],[\n0588/BNO\n],NaN
Gearing Type,"[\n, Automatic, \n]","[\n, Manual, \n]","[\n, Automatic, \n]"
Displacement,[\n999 cc\n],[\n999 cc\n],"[\n1,598 cc\n]"
Cylinders,NaN,NaN,NaN
Weight,"[\n1,200 kg\n]","[\n1,180 kg\n]",NaN
Drive chain,[\nfront\n],NaN,[\nfront\n]
Fuel,"[\n, Super 95, \n]","[\n, Super 95, \n]","[\n, Diesel (Particulate Filter), \n]"
Consumption,"[[4.8 l/100 km (comb)], [5.9 l/100 km (city)],...","[[4.9 l/100 km (comb)], [6 l/100 km (city)], [...","[[4.5 l/100 km (comb)], [5.7 l/100 km (city)],..."
CO2 Emission,[\n110 g CO2/km (comb)\n],[\n116 g CO2/km (comb)\n],[\n119 g CO2/km (comb)\n]
Emission Class,[\nEuro 6\n],[\nEuro 6d-TEMP\n],[\nEuro 6\n]
\nComfort & Convenience\n,"[Air conditioning, Armrest, Electrical side mi...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Cruise control, Electrical ..."
\nEntertainment & Media\n,"[Bluetooth, Hands-free equipment]","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, CD player, Hands-free equipment, O..."
\nExtras\n,[Alloy wheels],"[Alloy wheels, Voice Control]","[Roof rack, Touch screen]"
\nSafety & Security\n,"[Daytime running lights, Driver-side airbag, E...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light..."
description,"[\n, Ausstattungspakete:, Lichtpaket, Nichtra...","[\n, Assistenzsysteme:, Spracheingabesystem, ...","[\n, Sehr geehrte Kundin, sehr geehrter Kunde,..."
Emission Label,NaN,NaN,NaN
Gears,NaN,NaN,NaN
Country version,[\nGermany\n],NaN,NaN
Electricity consumption,NaN,NaN,NaN
Last Service Date,NaN,NaN,NaN
Other Fuel Types,NaN,NaN,NaN
Availability,NaN,NaN,NaN
Last Timing Belt Service Date,NaN,NaN,NaN
Available from,NaN,NaN,NaN

In [7]:
df.shape

(15919, 54)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   make_model                     15919 non-null  object
 2   short_description              15873 non-null  object
 3   body_type                      15859 non-null  object
 4   price                          15919 non-null  int64
 5   vat                            11406 non-null  object
 6   km                             15919 non-null  object
 7   registration                   15919 non-null  object
 8   prev_owner                     9091 non-null   object
 9   kW                             0 non-null      float64
 10  hp                             15919 non-null  object
 11  Type                           15917 non-null  object
 12  Previous Owners                9279 non-null   object
 13  Next Inspection                3535 non-null   object
 14  Inspection new                 3932 non-null   object
 15  Warranty                       10499 non-null  object
 16  Full Service                   8215 non-null   object
 17  Non-smoking Vehicle            7177 non-null   object
 18  null                           15919 non-null  object
 19  Make                           15919 non-null  object
 20  Model                          15919 non-null  object
 21  Offer Number                   12744 non-null  object
 22  First Registration             14322 non-null  object
 23  Body Color                     15322 non-null  object
 24  Paint Type                     10147 non-null  object
 25  Body Color Original            12160 non-null  object
 26  Upholstery                     12199 non-null  object
 27  Body                           15859 non-null  object
 28  Nr. of Doors                   15707 non-null  object
 29  Nr. of Seats                   14942 non-null  object
 30  Model Code                     4978 non-null   object
 31  Gearing Type                   15919 non-null  object
 32  Displacement                   15423 non-null  object
 33  Cylinders                      10239 non-null  object
 34  Weight                         8945 non-null   object
 35  Drive chain                    9061 non-null   object
 36  Fuel                           15919 non-null  object
 37  Consumption                    14013 non-null  object
 38  CO2 Emission                   14111 non-null  object
 39  Emission Class                 12898 non-null  object
 40
Comfort & Convenience
        14999 non-null  object
 41
Entertainment & Media
        14545 non-null  object
 42
Extras
                       12957 non-null  object
 43
Safety & Security
            14937 non-null  object
 44  description                    15919 non-null  object
 45  Emission Label                 3985 non-null   object
 46  Gears                          11207 non-null  object
 47  Country version                7586 non-null   object
 48  Electricity consumption        137 non-null    object
 49  Last Service Date              566 non-null    object
 50  Other Fuel Types               880 non-null    object
 51  Availability                   635 non-null    object
 52  Last Timing Belt Service Date  16 non-null     object
 53  Available from                 272 non-null    object
dtypes: float64(1), int64(1), object(52)
memory usage: 6.6+ MB

In [35]:
df.make_model.value_counts()

Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64

In [36]:
df.short_description.value_counts()

SPB 1.6 TDI 116 CV S tronic Sport                 64
1.4 66kW (90CV) Selective                         40
MOVE KLIMA CD USB ALLWETTER BLUETOOTH             38
SPB 30 TDI S tronic Business                      35
SPB 30 TFSI S tronic Admired                      35
                                                  ..
K Sports Tourer Business **Navi*Voll**             1
1.0 Turbo ecoFLEX Automatic Elective Park Navi     1
1.6 CDTI Business *Navi*Automatik*Spurh.*          1
1.6 136 CV Automatica Navi E 6 Garanzia Full       1
TCe 225 EDC GPF LIM Deluxe Pano,RFK                1
Name: short_description, Length: 10001, dtype: int64

In [41]:
df[["short_description","description"]].head(15)

,short_description,description
0,Sportback 1.4 TDI S-tronic Xenon Navi Klima,"[\n, Sicherheit:, , Deaktivierung für Beifahr..."
1,1.8 TFSI sport,[\nLangstreckenfahrzeug daher die hohe Kilomet...
2,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2..."
3,1.4 TDi Design S tronic,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat..."
4,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa..."
5,1.6 TDI Sport DSG *SHZ*Xenon*Navi*Bose*PDC*,[\nSichern Sie sich diesen Audi A1 1.6 TDI Spo...
6,Sportback 1.6 TDI S-TRONIC S-LINE*NAVI|XENON*,"[\nREDUZIERT !!!, MwSt. ausweisbar, Nettopreis..."
7,Sportback 1.4 TDI admired S tronic,"[\n, Ausstattungspakete:, Ausstattungspaket: ..."
8,SPB 1.6 TDI S-tronic Metal plus + Xeno,[\nAuto in ottime condizioni. Unico proprietar...
9,SPORTBACK TFSI ULTRA 95 S-TRONIC AMB.,"[\nClim automatique,Ecran multifonction couleu..."
10,SPORTBACK1.6 TDI 116 CV S tronic Metal plus,"[\nautovettura ufficiale unico proprietario , ..."
11,Sportback Sport »1.4 TFSI|Xenon|Navi|EPH+|SHZ|...,"[\n, Außenausstattung, beheizbare Außenspiegel..."
12,Sportback 1.4 TFSI S-tronic *S line*NAV*XEN*,"[\n, Highlights:, Anschlussgarantie 1 Jahr, ma..."
13,1.4 TFSI 150ch COD Ambition Luxe S tronic 7,[\nMarque: AUDIModèle: A1Version: 1.4 TFSI 150...
14,Sportback 1.0 TFSI S-TRonic*Navi*Xenon*APS* Sport,"[\n, www.nord-automobile.de, AUDI A1 1.0 TFSI..."

In [38]:
df[["short_description","description"]].sample(15)
#bunlar ne kadar uyumlu bir komtrol edilsin kimi yerde uyumlu kimi yerde degil?

,short_description,description
9034,1.2cc cdti 75DKM nw model 5D airco euro6 zuini...,"[\nOpel Corsa Cdti 1.2cc Ecoflex 5deurs 2016, ..."
6527,Edition - 1.0 Turbo - 105PK - AUTOMAAT,"[\nSleepvermogen 1230 kg – , 12 maanden garant..."
8281,1.4i 120 Years (EU6.2),[\nAuto wordt verkocht doordat mijn schoonmoed...
744,SPORTBACK S line,"[\n, AGENCE SIMPLICI CAR TERNES PORTE MAILLOT ..."
8721,"E Selection, 3-Türer 1.2, 51 kW (69 PS)","[\nFahrzeug-ID: 5003960, Standort: Herne, Seri..."
3223,"Sportback Ambiente 1,6 TDI*XENON*","[\n, Audi A3 Ambiente Sportback 1,6 TDI aus 20..."
13503,1.5 dCi 75ch energy Business Eco² Euro6 2015,[\nBlanc Glacier ABS Aide au démarrage en côte...
11844,ST 1.5 Turbo Innovation NAVI LED EU6,"[\nFahrzeug-Nr.: 1114815., Media:, 3D-Kartenda..."
4970,3ª serie SPB 1.6 TDI 116 CV Sport,"[\nDEK:[2736524], La dotazione tecnica e gli o..."
10108,E 120 Jahre Aut. | Feelgood-Paket | Regens,"[\n, E10 geeignet, Interieurfarbe Schwarz, Int..."
9830,"""1 4 66kW (90CV) Selective""","[\n""LlÃ¡manos 683111093., AutomÃ²bils Bertran...."
265,Sportback design 1.0TFSI Media/SHZ/APS PDC LM K,"[\n, Ausstattungspakete:, Nichtraucherpaket, ..."
15791,V dCi 160 Energy Twin Turbo,[\nV dCi 160 Energy Twin Turbo Initiale Paris ...
14101,1.5 dCi 8V 75CV NEO PATENTATI OK,[]
9162,1.3 CDTI N-JOY,"[\n, OCCASIONE OPEL CORSA 3P. 1.3 75cv ADATTA ..."

In [40]:
df.description

0        [\n, Sicherheit:,  , Deaktivierung für Beifahr...
1        [\nLangstreckenfahrzeug daher die hohe Kilomet...
2        [\n, Fahrzeug-Nummer: AM-95365,  , Ehem. UPE 2...
3        [\nAudi A1: , - 1e eigenaar , - Perfecte staat...
4        [\n, Technik & Sicherheit:, Xenon plus, Klimaa...
                               ...
15914    [\nVettura visionabile nella sede in Via Roma ...
15915    [\nDach: Panorama-Glas-Schiebedach, Lackierung...
15916    [\n, Getriebe:,  Automatik, Technik:,  Bordcom...
15917    [\nDEK:[2691331], Renault Espace Blue dCi 200C...
15918    [\n, Sicherheit Airbags:,  , Seitenairbag,  , ...
Name: description, Length: 15919, dtype: object

In [ ]:
def missing (df):     
    missing_number = df.isnull().sum().sort_values(ascending=False)  #it shows total NaN values in each column
    missing_percent = (df.isnull().sum()/len(df)*100).sort_values(ascending=False)     
    missing_values = pd.concat([missing_number, missing_percent], axis=1, keys=['Missing_Number', 'Missing_Percent'])
    return missing_values

missing(df)

In [9]:
df.describe()

              price   kW
count  15919.000000  0.0
mean   18019.896727  NaN
std     7386.169409  NaN
min       13.000000  NaN
25%    12850.000000  NaN
50%    16900.000000  NaN
75%    21900.000000  NaN
max    74600.000000  NaN

In [22]:
df.describe(include="object").T

,count,unique,top,freq
url,15919,15919,https://www.autoscout24.com//offers/audi-a1-sp...,1
make_model,15919,9,Audi A3,3097
short_description,15873,10001,SPB 1.6 TDI 116 CV S tronic Sport,64
body_type,15859,9,Sedans,7903
vat,11406,2,VAT deductible,10980
km,15919,6690,10 km,1045
registration,15919,48,-/-,1597
prev_owner,9091,4,1 previous owner,8294
hp,15919,81,85 kW,2542
Type,15917,169,"[, Used, , Diesel (Particulate Filter)]",3475
Previous Owners,9279,102,\n1\n,8101
Next Inspection,3535,1399,\n04/2022\n,62
Inspection new,3932,202,"[\nYes\n, \nEuro 6\n]",523
Warranty,10499,515,"[\n, \n, \nEuro 6\n]",1868
Full Service,8215,122,"[\n, \n, \n4 (Green)\n]",2235
Non-smoking Vehicle,7177,94,"[\n, \n]",3647
null,15919,1,[],15919
Make,15919,3,\nOpel\n,7343
Model,15919,9,"[\n, A3, \n]",3097
Offer Number,12744,11440,[\nLT67679\n],27
First Registration,14322,4,"[\n, 2018, \n]",4522
Body Color,15322,14,"[\n, Black, \n]",3745
Paint Type,10147,3,[\nMetallic\n],9794
Body Color Original,12160,1927,[\nOnyx Schwarz\n],338
Upholstery,12199,46,"[\nCloth, Black\n]",5821
Body,15859,9,"[\n, Sedans, \n]",7903
Nr. of Doors,15707,6,[\n5\n],11575
Nr. of Seats,14942,6,[\n5\n],13336
Model Code,4978,232,[\n0035/BCB\n],268
Gearing Type,15919,3,"[\n, Manual, \n]",8153
Displacement,15423,77,"[\n1,598 cc\n]",4761
Cylinders,10239,7,[\n4\n],8105
Weight,8945,434,"[\n1,163 kg\n]",574
Drive chain,9061,3,[\nfront\n],8886
Fuel,15919,77,"[\n, Diesel (Particulate Filter), \n]",4315
Consumption,14013,881,"[[3.9 l/100 km (comb)], [4.1 l/100 km (city)],...",304
CO2 Emission,14111,123,[\n120 g CO2/km (comb)\n],740
Emission Class,12898,7,[\nEuro 6\n],10139
\nComfort & Convenience\n,14999,6198,"[Air conditioning, Electrical side mirrors, Hi...",216
\nEntertainment & Media\n,14545,346,"[Bluetooth, Hands-free equipment, On-board com...",1282
\nExtras\n,12957,659,[Alloy wheels],3245
\nSafety & Security\n,14937,4443,"[ABS, Central door lock, Daytime running light...",538
description,15919,12874,[],636
Emission Label,3985,6,[\n4 (Green)\n],3553
Gears,11207,10,[\n6\n],5822
Country version,7586,23,[\nGermany\n],4502
Electricity consumption,137,1,[\n0 kWh/100 km (comb)\n],137
Last Service Date,566,266,"[\n02/2019\n, \nEuro 6\n]",23
Other Fuel Types,880,1,"[[], [], []]",880
Availability,635,15,\nin 90 days from ordering\n,196
Last Timing Belt Service Date,16,15,[\n04/2016\n],2
Available from,272,46,\n31/08/19\n,98

In [43]:
df.body_type.value_counts()#nbu temizmis ve budy il baglantili body kirli bunu tut

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [45]:
df.Type.value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[, Used, , Diesel (Particulate Filter)]                                                                                 3475
[, Used, , Diesel]                                                                                                      2516
[, Used, , Gasoline]                                                                                                    2367
[, Used, , Super 95]                                                                                                    1818
[, Pre-registered, , Super 95]                                                                                           500
                                                                                                                        ...
[, New, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95]       1
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                               1
[, Demonstration, , Super Plus 98]                                                                                         1
[, New, , Super Plus E10 98]                                                                                               1
[, Demonstration, , Regular/Benzine E10 91]                                                                                1
Name: Type, Length: 169, dtype: int64

In [46]:
df.Body.value_counts()#bu kirli bunu drop et

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Sedans, \n]           7903
[\n, Station wagon, \n]    3553
[\n, Compact, \n]          3153
[\n, Van, \n]               783
[\n, Other, \n]             290
[\n, Transporter, \n]        88
[\n, Off-Road, \n]           56
[\n, Coupe, \n]              25
[\n, Convertible, \n]         8
Name: Body, dtype: int64

In [32]:
df.vat.nunique

<bound method IndexOpsMixin.nunique of 0          VAT deductible
1        Price negotiable
2          VAT deductible
3                    None
4                    None
               ...
15914      VAT deductible
15915      VAT deductible
15916      VAT deductible
15917      VAT deductible
15918      VAT deductible
Name: vat, Length: 15919, dtype: object>

In [47]:
df.vat.value_counts()# birinciell olmasi 2. el olmasi
#none gercekten bosmu yoksa hic indirim yapilmamis mi 
#green ya co2 emisyon ile alakali

VAT deductible      10980
Price negotiable      426
Name: vat, dtype: int64

In [16]:
df.isnull().sum()

url                                  0
make_model                           0
short_description                   46
body_type                           60
price                                0
vat                               4513
km                                   0
registration                         0
prev_owner                        6828
kW                               15919
hp                                   0
Type                                 2
Previous Owners                   6640
Next Inspection                  12384
Inspection new                   11987
Warranty                          5420
Full Service                      7704
Non-smoking Vehicle               8742
null                                 0
Make                                 0
Model                                0
Offer Number                      3175
First Registration                1597
Body Color                         597
Paint Type                        5772
Body Color Original               3759
Upholstery                        3720
Body                                60
Nr. of Doors                       212
Nr. of Seats                       977
Model Code                       10941
Gearing Type                         0
Displacement                       496
Cylinders                         5680
Weight                            6974
Drive chain                       6858
Fuel                                 0
Consumption                       1906
CO2 Emission                      1808
Emission Class                    3021
\nComfort & Convenience\n          920
\nEntertainment & Media\n         1374
\nExtras\n                        2962
\nSafety & Security\n              982
description                          0
Emission Label                   11934
Gears                             4712
Country version                   8333
Electricity consumption          15782
Last Service Date                15353
Other Fuel Types                 15039
Availability                     15284
Last Timing Belt Service Date    15903
Available from                   15647
dtype: int64

In [51]:
df.iloc[388]#none  olan arabalar ortakmi ;luksmu bu arastirilsin

url                              https://www.autoscout24.com//offers/audi-a1-s1...
make_model                                                                 Audi A1
short_description                                  /S1 SPB 1.6 TDI 116 CV S tronic
body_type                                                                   Sedans
price                                                                        15990
vat                                                                           None
km                                                                       73,575 km
registration                                                               01/2016
prev_owner                                                                    None
kW                                                                             NaN
hp                                                                           85 kW
Type                                                            [, Used, , Diesel]
Previous Owners                                                                NaN
Next Inspection                                                                NaN
Inspection new                                                                 NaN
Warranty                                                                       NaN
Full Service                                                                   NaN
Non-smoking Vehicle                                                            NaN
null                                                                            []
Make                                                                      \nAudi\n
Model                                                                 [\n, A1, \n]
Offer Number                                                                   NaN
First Registration                                                  [\n, 2016, \n]
Body Color                                                         [\n, Black, \n]
Paint Type                                                          [\nMetallic\n]
Body Color Original                                                            NaN
Upholstery                                                                     NaN
Body                                                              [\n, Sedans, \n]
Nr. of Doors                                                               [\n5\n]
Nr. of Seats                                                                   NaN
Model Code                                                                     NaN
Gearing Type                                                   [\n, Automatic, \n]
Displacement                                                        [\n1,598 cc\n]
Cylinders                                                                  [\n4\n]
Weight                                                                         NaN
Drive chain                                                            [\nfront\n]
Fuel                                                              [\n, Diesel, \n]
Consumption                      [[4.3 l/100 km (comb)], [3.7 l/100 km (city)],...
CO2 Emission                                              [\n97 g CO2/km (comb)\n]
Emission Class                                                        [\nEuro 6\n]
\nComfort & Convenience\n        [Air conditioning, Automatic climate control, ...
\nEntertainment & Media\n                                                      NaN
\nExtras\n                                                          [Alloy wheels]
\nSafety & Security\n            [ABS, Driver-side airbag, Power steering, Trac...
description                      [\nDisponibile presso GMG Spa Via della Romagn...
Emission Label                                                                 NaN
Gears                                                                      [\n7\n]
Country version                                                                NaN
Electricity consumption                                                        NaN
Last Service Date                                                              NaN
Other Fuel Types                                                               NaN
Availability                                                                   NaN
Last Timing Belt Service Date                                                  NaN
Available from                                                                 NaN
Name: 388, dtype: object

In [52]:
df.iloc[422]

url                              https://www.autoscout24.com//offers/audi-a1-1-...
make_model                                                                 Audi A1
short_description                             1.4 TDI Design DKG*Navi*PDC*Alu*SHZ*
body_type                                                                  Compact
price                                                                        14990
vat                                                                           None
km                                                                       49,351 km
registration                                                               12/2016
prev_owner                                                       2 previous owners
kW                                                                             NaN
hp                                                                           66 kW
Type                                       [, Used, , Diesel (Particulate Filter)]
Previous Owners                                                              \n2\n
Next Inspection                                                                NaN
Inspection new                                                                 NaN
Warranty                                                                       NaN
Full Service                                     [\n, \n, \n104 g CO2/km (comb)\n]
Non-smoking Vehicle                                           [\n, \n, \nEuro 6\n]
null                                                                            []
Make                                                                      \nAudi\n
Model                                                                 [\n, A1, \n]
Offer Number                                                         [\nAK13780\n]
First Registration                                                  [\n, 2016, \n]
Body Color                                                         [\n, Black, \n]
Paint Type                                                          [\nMetallic\n]
Body Color Original                                                            NaN
Upholstery                                                       [\nCloth, Grey\n]
Body                                                             [\n, Compact, \n]
Nr. of Doors                                                               [\n4\n]
Nr. of Seats                                                               [\n5\n]
Model Code                                                                     NaN
Gearing Type                                                   [\n, Automatic, \n]
Displacement                                                        [\n1,422 cc\n]
Cylinders                                                                      NaN
Weight                                                                         NaN
Drive chain                                                                    NaN
Fuel                                         [\n, Diesel (Particulate Filter), \n]
Consumption                      [[4 l/100 km (comb)], [4.4 l/100 km (city)], [...
CO2 Emission                                             [\n104 g CO2/km (comb)\n]
Emission Class                                                        [\nEuro 6\n]
\nComfort & Convenience\n        [Air conditioning, Armrest, Automatic climate ...
\nEntertainment & Media\n        [Bluetooth, CD player, Hands-free equipment, O...
\nExtras\n                              [Alloy wheels, Sport seats, Voice Control]
\nSafety & Security\n            [ABS, Central door lock, Daytime running light...
description                      [\n, Fahrzeugbeschreibung,  Sichern Sie sich d...
Emission Label                                                     [\n4 (Green)\n]
Gears                                                                          NaN
Country version                                                      [\nGermany\n]
Electricity consumption                                                        NaN
Last Service Date                                                              NaN
Other Fuel Types                                                               NaN
Availability                                                                   NaN
Last Timing Belt Service Date                                                  NaN
Available from                                                                 NaN
Name: 422, dtype: object

In [35]:
df.vat.sample(15)

8027     VAT deductible
5984     VAT deductible
7693     VAT deductible
14697    VAT deductible
14215    VAT deductible
388                None
422                None
2744     VAT deductible
9740     VAT deductible
3680               None
8445     VAT deductible
15222    VAT deductible
4376     VAT deductible
14001    VAT deductible
14117              None
Name: vat, dtype: object

In [39]:
df.vat.isnull().sum()

4513

In [53]:
df.km.isnull().sum()

0

In [54]:
df.km.value_counts()#kalsin ama virgul falan silinecek icin duzenlencecek

10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ...
67,469 km       1
43,197 km       1
10,027 km       1
35,882 km       1
57 km           1
Name: km, Length: 6690, dtype: int64

In [56]:
df["registration"].sample()

3900    05/2017
Name: registration, dtype: object

In [57]:
df["registration"].value_counts()

-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
01/2019     541
04/2018     541
02/2018     539
03/2016     536
04/2016     532
06/2018     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
08/2019       1
11/2019       1
12/2019       1
Name: registration, dtype: int64

In [47]:
df["First Registration"].sample()

7762    [\n, 2019, \n]
Name: First Registration, dtype: object

In [48]:
df[["registration","First Registration"]].sample(15)
#first regstration delete edilebilir ayni bilgiyi icermekte
#ama burda eger sadce tarih onemliyse first registrationu cekmek daha mantikli cunku liste halinde 
#split yap 1nciyi al

      registration First Registration
2668       11/2016     [\n, 2016, \n]
5025       02/2019     [\n, 2019, \n]
11012      06/2016     [\n, 2016, \n]
11480      03/2018     [\n, 2018, \n]
13481      02/2017     [\n, 2017, \n]
8568       06/2016     [\n, 2016, \n]
12164      02/2018     [\n, 2018, \n]
10304          -/-                NaN
8392       06/2018     [\n, 2018, \n]
12511      03/2019     [\n, 2019, \n]
15444          -/-                NaN
1481       07/2018     [\n, 2018, \n]
7240       09/2018     [\n, 2018, \n]
2503           -/-                NaN
14446      08/2018     [\n, 2018, \n]

In [32]:
#from scipy.stats import linregress
#linregress("registration", "First Registration")

In [31]:
#np.corrcoef("registration", "First Registration")

In [30]:
#def corr("registration","First Registration"):
  #  "data1 & data2 should be numpy arrays."
    #mean1 = ["registration,"].mean() 
    #mean2 = ["First Registration"].mean()
    #std1 = ["registration,"].std()
    #std2 =["First Registration"].std()

#     corr = ((data1-mean1)*(data2-mean2)).mean()/(std1*std2)
    #corr = ((["registration"]*["First Registration"].mean()-mean1*mean2)/(std1*std2)
   # return corr

In [58]:
df.prev_owner.value_counts()

1 previous owner     8294
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64

In [60]:
df.prev_owner.isnull().sum()

6828

In [61]:
df[["prev_owner","Previous Owners"]].sample(15)

             prev_owner Previous Owners
2665   1 previous owner           \n1\n
12212  1 previous owner           \n1\n
15868              None             NaN
12521              None             NaN
6894   1 previous owner           \n1\n
11235  1 previous owner           \n1\n
8082               None             NaN
2065               None             NaN
12063  1 previous owner           \n1\n
12672              None             NaN
13664  1 previous owner           \n1\n
5167               None             NaN
6565   1 previous owner           \n1\n
2280   1 previous owner           \n1\n
1062   1 previous owner           \n1\n

In [64]:
df["Previous Owners"]

0                                                    \n2\n
1                                                      NaN
2                                                    \n1\n
3                                                    \n1\n
4                                                    \n1\n
                               ...
15914                                                  NaN
15915    [\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100...
15916                     [\n1\n, \n139 g CO2/km (comb)\n]
15917                                                  NaN
15918                                                \n1\n
Name: Previous Owners, Length: 15919, dtype: object

In [66]:
df["Previous Owners"].isnull().sum()

6640

In [49]:
df.prev_owner.describe()
#onceki kullanicilar onemli o yuzden kalsin dedik

count                 9091
unique                   4
top       1 previous owner
freq                  8294
Name: prev_owner, dtype: object

In [67]:
df.km.isnull().sum()

0

In [68]:
df.km.value_counts()

10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ...
67,469 km       1
43,197 km       1
10,027 km       1
35,882 km       1
57 km           1
Name: km, Length: 6690, dtype: int64

In [61]:
df.km.describe()

count     15919
unique     6690
top       10 km
freq       1045
Name: km, dtype: object

In [69]:
df.kW.value_counts()

Series([], Name: kW, dtype: int64)

In [62]:
df.kW.describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: kW, dtype: float64

In [70]:
df.kW.isnull().sum()

15919

In [63]:
df.hp.describe()

count     15919
unique       81
top       85 kW
freq       2542
Name: hp, dtype: object

In [71]:
df.hp.isnull().sum()

0

In [72]:
df.hp.value_counts()

85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
          ...
84 kW        1
195 kW       1
44 kW        1
239 kW       1
9 kW         1
Name: hp, Length: 81, dtype: int64

In [67]:
df.hp.nunique()

81

In [69]:
df.hp.unique()

array(['66 kW', '141 kW', '85 kW', '70 kW', '92 kW', '112 kW', '60 kW',
       '71 kW', '67 kW', '110 kW', '93 kW', '147 kW', '86 kW', '140 kW',
       '87 kW', '- kW', '81 kW', '82 kW', '135 kW', '132 kW', '100 kW',
       '96 kW', '162 kW', '150 kW', '294 kW', '228 kW', '270 kW',
       '137 kW', '9 kW', '133 kW', '77 kW', '101 kW', '78 kW', '103 kW',
       '1 kW', '74 kW', '118 kW', '84 kW', '88 kW', '80 kW', '76 kW',
       '149 kW', '44 kW', '51 kW', '55 kW', '52 kW', '63 kW', '40 kW',
       '65 kW', '75 kW', '125 kW', '120 kW', '184 kW', '239 kW', '121 kW',
       '143 kW', '191 kW', '89 kW', '195 kW', '127 kW', '122 kW',
       '154 kW', '155 kW', '104 kW', '123 kW', '146 kW', '90 kW', '53 kW',
       '54 kW', '56 kW', '164 kW', '4 kW', '163 kW', '57 kW', '119 kW',
       '165 kW', '117 kW', '115 kW', '98 kW', '168 kW', '167 kW'],
      dtype=object)

In [78]:
df["Type"].describe()

count                                       15917
unique                                        169
top       [, Used, , Diesel (Particulate Filter)]
freq                                         3475
Name: Type, dtype: object

In [73]:
df.Type.value_counts()#burda 4 cesti varmis bu gruplanabilir liste duzenlenmeili

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[, Used, , Diesel (Particulate Filter)]                                                                                 3475
[, Used, , Diesel]                                                                                                      2516
[, Used, , Gasoline]                                                                                                    2367
[, Used, , Super 95]                                                                                                    1818
[, Pre-registered, , Super 95]                                                                                           500
                                                                                                                        ...
[, New, , Regular/Benzine 91 / Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95]       1
[, Used, , Super 95 / Super Plus 98 / Super E10 95 / Super Plus E10 98 (Particulate Filter)]                               1
[, Demonstration, , Super Plus 98]                                                                                         1
[, New, , Super Plus E10 98]                                                                                               1
[, Demonstration, , Regular/Benzine E10 91]                                                                                1
Name: Type, Length: 169, dtype: int64

In [74]:
df.Type.isnull().sum()

2

In [80]:
df[["prev_owner","Previous Owners"]].sample(15)

             prev_owner                                    Previous Owners
13935  1 previous owner                                              \n1\n
7911               None                                                NaN
4649   1 previous owner                                              \n1\n
11417  1 previous owner                                              \n1\n
7770   1 previous owner                                              \n1\n
467    1 previous owner                                              \n1\n
10901  1 previous owner                                              \n1\n
13429              None                                                NaN
1276   1 previous owner                                              \n1\n
6113   1 previous owner                                              \n1\n
13863              None                                                NaN
7715   1 previous owner                                              \n1\n
8098               None  [\n0\n, \n, 5.4 l/100 km (comb), \n, 7.1 l/100...
12075  1 previous owner                                              \n1\n
10623  1 previous owner                                              \n1\n

In [82]:
df["prev_owner"].unique()

array(['2 previous owners', None, '1 previous owner', '3 previous owners',
       '4 previous owners'], dtype=object)

In [84]:
df["prev_owner"].isnull().sum()

6828

In [75]:
df["prev_owner"].value_counts()

1 previous owner     8294
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64

In [76]:
df["Next Inspection"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

\n04/2022\n                               62
\n03/2021\n                               38
\n03/2022\n                               36
\n06/2021\n                               34
\n01/2022\n                               32
                                          ..
[\n12/2018\n, \n97 g CO2/km (comb)\n]      1
[\n03/2022\n, \n1 (No sticker)\n]          1
[\n05/2021\n, \n93 g CO2/km (comb)\n]      1
[\n06/2021\n, \n93 g CO2/km (comb)\n]      1
[\n01/2022\n, \n168 g CO2/km (comb)\n]     1
Name: Next Inspection, Length: 1399, dtype: int64

In [79]:
df["Next Inspection"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

\n04/2022\n                               62
\n03/2021\n                               38
\n03/2022\n                               36
\n06/2021\n                               34
\n01/2022\n                               32
                                          ..
[\n12/2018\n, \n97 g CO2/km (comb)\n]      1
[\n03/2022\n, \n1 (No sticker)\n]          1
[\n05/2021\n, \n93 g CO2/km (comb)\n]      1
[\n06/2021\n, \n93 g CO2/km (comb)\n]      1
[\n01/2022\n, \n168 g CO2/km (comb)\n]     1
Name: Next Inspection, Length: 1399, dtype: int64

In [77]:
df[["Inspection new","Next Inspection"]].isnull().sum()

Inspection new     11987
Next Inspection    12384
dtype: int64

In [86]:
df[["Inspection new","Next Inspection"]].sample(15)

,Inspection new,Next Inspection
4163,NaN,"[\n03/2021\n, \n107 g CO2/km (comb)\n]"
5231,"[\nYes\n, \n117 g CO2/km (comb)\n]",NaN
13206,NaN,NaN
12491,"[\nYes\n, \n180 g CO2/km (comb)\n]",NaN
1065,NaN,NaN
11799,NaN,NaN
5662,"[\nYes\n, \n0 kWh/100 km (comb)\n]",NaN
4528,NaN,"[\n04/2021\n, \n111 g CO2/km (comb)\n]"
4439,NaN,"[\n05/2021\n, \n108 g CO2/km (comb)\n]"
6514,NaN,NaN
473,NaN,"[\n03/2021\n, \n0 kWh/100 km (comb)\n]"
11237,NaN,NaN
2621,NaN,NaN
4591,NaN,NaN
7093,NaN,"[\n01/2019\n, \n128 g CO2/km (comb)\n]"

In [88]:
df[["Inspection new","Next Inspection"]].isnull().sum()#yil 1. el 2. el olmasi gibi conditionlara gore yil doldurulcak

Inspection new     11987
Next Inspection    12384
dtype: int64

In [81]:
df["CO2 Emission"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n120 g CO2/km (comb)\n]      740
[[], [], []]                   628
[\n99 g CO2/km (comb)\n]       545
[\n97 g CO2/km (comb)\n]       537
[\n104 g CO2/km (comb)\n]      501
                              ...
[\n14 g CO2/km (comb)\n]         1
[\n1,060 g CO2/km (comb)\n]      1
[\n51 g CO2/km (comb)\n]         1
[\n165 g CO2/km (comb)\n]        1
[\n193 g CO2/km (comb)\n]        1
Name: CO2 Emission, Length: 123, dtype: int64

In [82]:
df[["Inspection new","Next Inspection","CO2 Emission"]]

,Inspection new,Next Inspection,CO2 Emission
0,"[\nYes\n, \nEuro 6\n]","[\n06/2021\n, \n99 g CO2/km (comb)\n]",[\n99 g CO2/km (comb)\n]
1,NaN,NaN,[\n129 g CO2/km (comb)\n]
2,NaN,NaN,[\n99 g CO2/km (comb)\n]
3,NaN,NaN,[\n99 g CO2/km (comb)\n]
4,"[\nYes\n, \n109 g CO2/km (comb)\n]",NaN,[\n109 g CO2/km (comb)\n]
...,...,...,...
15914,NaN,NaN,[\n139 g CO2/km (comb)\n]
15915,NaN,"[\n01/2022\n, \n168 g CO2/km (comb)\n]",[\n168 g CO2/km (comb)\n]
15916,"[\nYes\n, \nEuro 6d-TEMP\n]",NaN,[\n139 g CO2/km (comb)\n]
15917,NaN,NaN,[\n139 g CO2/km (comb)\n]
15918,"[\nYes\n, \n153 g CO2/km (comb)\n]",NaN,[\n153 g CO2/km (comb)\n]

In [83]:
df[["Next Inspection","Inspection new", 'CO2 Emission', 'Emission Class']].head()

,Next Inspection,Inspection new,CO2 Emission,Emission Class
0,"[\n06/2021\n, \n99 g CO2/km (comb)\n]","[\nYes\n, \nEuro 6\n]",[\n99 g CO2/km (comb)\n],[\nEuro 6\n]
1,NaN,NaN,[\n129 g CO2/km (comb)\n],[\nEuro 6\n]
2,NaN,NaN,[\n99 g CO2/km (comb)\n],[\nEuro 6\n]
3,NaN,NaN,[\n99 g CO2/km (comb)\n],[\nEuro 6\n]
4,NaN,"[\nYes\n, \n109 g CO2/km (comb)\n]",[\n109 g CO2/km (comb)\n],[\nEuro 6\n]

In [84]:
df[["Next Inspection","Inspection new", 'CO2 Emission', 'Emission Class']].isnull().sum()

Next Inspection    12384
Inspection new     11987
CO2 Emission        1808
Emission Class      3021
dtype: int64

In [90]:
df[["Next Inspection","Inspection new", 'CO2 Emission', 'Emission Class']].sample(10)

,Next Inspection,Inspection new,CO2 Emission,Emission Class
13394,NaN,NaN,[\n92 g CO2/km (comb)\n],[\nEuro 6\n]
15837,NaN,NaN,[\n123 g CO2/km (comb)\n],[\nEuro 6\n]
5124,NaN,"[\nYes\n, \n117 g CO2/km (comb)\n]",[\n117 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n]
5953,NaN,"[\nYes\n, \n119 g CO2/km (comb)\n]",[\n119 g CO2/km (comb)\n],[\nEuro 6\n]
11688,"[\n05/2021\n, \n4 (Green)\n]",NaN,NaN,"[[], [], []]"
7383,NaN,NaN,[\n133 g CO2/km (comb)\n],[\nEuro 6\n]
629,"[\n06/2021\n, \n109 g CO2/km (comb)\n]","[\nYes\n, \nEuro 6\n]",[\n109 g CO2/km (comb)\n],[\nEuro 6\n]
14696,NaN,NaN,[\n113 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n]
8197,\n01/2022\n,NaN,[\n112 g CO2/km (comb)\n],NaN
2170,\n01/2022\n,"[\nYes\n, \n123 g CO2/km (comb)\n]",[\n123 g CO2/km (comb)\n],[\nEuro 6\n]

In [92]:
df[["Next Inspection","Inspection new", 'CO2 Emission', 'Emission Class',"First Registration"]].sample(10)
#baska yil ile baglanti kurulmali

,Next Inspection,Inspection new,CO2 Emission,Emission Class,First Registration
10882,NaN,\nYes\n,[\n103 g CO2/km (comb)\n],[\nEuro 6\n],"[\n, 2016, \n]"
6898,"[\n12/2019\n, \n102 g CO2/km (comb)\n]",NaN,[\n102 g CO2/km (comb)\n],[\nEuro 6\n],"[\n, 2017, \n]"
405,\n04/2020\n,NaN,[\n99 g CO2/km (comb)\n],[\nEuro 6\n],"[\n, 2017, \n]"
974,NaN,NaN,[\n110 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n],NaN
1524,NaN,"[\nYes\n, \n102 g CO2/km (comb)\n]",[\n102 g CO2/km (comb)\n],[\nEuro 6\n],"[\n, 2018, \n]"
6123,NaN,NaN,[\n133 g CO2/km (comb)\n],[\nEuro 6\n],"[\n, 2016, \n]"
9968,NaN,NaN,[\n143 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n],"[\n, 2019, \n]"
2640,NaN,NaN,NaN,NaN,"[\n, 2016, \n]"
4919,NaN,NaN,[\n108 g CO2/km (comb)\n],[\nEuro 6\n],"[\n, 2018, \n]"
14381,\n08/2022\n,NaN,[\n120 g CO2/km (comb)\n],[\nEuro 6\n],"[\n, 2018, \n]"

In [93]:
df[["Next Inspection","Warranty","Inspection new", "CO2 Emission", "Emission Class"]].sample(10)

,Next Inspection,Warranty,Inspection new,CO2 Emission,Emission Class
13907,NaN,"[\n12 months\n, \n85 g CO2/km (comb)\n]",NaN,[\n85 g CO2/km (comb)\n],[\nEuro 6\n]
7004,NaN,"[\n12 months\n, \n107 g CO2/km (comb)\n]",NaN,[\n107 g CO2/km (comb)\n],[\nEuro 6\n]
14487,NaN,"[\n, \n, \n113 g CO2/km (comb)\n]",NaN,[\n113 g CO2/km (comb)\n],[\nEuro 6d\n]
15773,NaN,NaN,NaN,[\n153 g CO2/km (comb)\n],[\nEuro 6\n]
10947,NaN,"[\n12 months\n, \nEuro 6\n]","[\nYes\n, \n119 g CO2/km (comb)\n]",[\n119 g CO2/km (comb)\n],[\nEuro 6\n]
9625,NaN,"[\n12 months\n, \n128 g CO2/km (comb)\n]",NaN,[\n128 g CO2/km (comb)\n],[\nEuro 6\n]
13055,"[\n04/2021\n, \n92 g CO2/km (comb)\n]",NaN,NaN,[\n92 g CO2/km (comb)\n],[\nEuro 6\n]
524,NaN,\n,NaN,[\n99 g CO2/km (comb)\n],[\nEuro 6\n]
7731,NaN,"[\n, \n, \n139 g CO2/km (comb)\n]","[\nYes\n, \n, 6.1 l/100 km (comb), \n, 7.5 l/1...",[\n139 g CO2/km (comb)\n],NaN
4239,NaN,\n48 months\n,NaN,[\n107 g CO2/km (comb)\n],[\nEuro 6\n]

In [90]:
df.Warranty.isnull().sum()

5420

In [94]:
df.Warranty.unique

<bound method Series.unique of 0                 [\n, \n, \n4 (Green)\n]
1                                     NaN
2        [\n, \n, \n99 g CO2/km (comb)\n]
3                                     NaN
4                    [\n, \n, \nEuro 6\n]
                       ...
15914                       \n24 months\n
15915                [\n, \n, \nEuro 6\n]
15916             [\n, \n, \n4 (Green)\n]
15917                                  \n
15918                                 NaN
Name: Warranty, Length: 15919, dtype: object>

In [95]:
df[["Next Inspection","Warranty","Inspection new", "CO2 Emission", "Emission Class"]].sample(10)

,Next Inspection,Warranty,Inspection new,CO2 Emission,Emission Class
15150,NaN,"[\n12 months\n, \n120 g CO2/km (comb)\n]",NaN,[\n120 g CO2/km (comb)\n],[\nEuro 6\n]
6730,NaN,"[\n, \n, \n92 g CO2/km (comb)\n]",NaN,[\n92 g CO2/km (comb)\n],[\nEuro 6\n]
5522,NaN,"[\n24 months\n, \n134 g CO2/km (comb)\n]",NaN,[\n134 g CO2/km (comb)\n],[\nEuro 6\n]
15691,NaN,"[\n, \n, \nEuro 6\n]","[\nYes\n, \n168 g CO2/km (comb)\n]",[\n168 g CO2/km (comb)\n],[\nEuro 6\n]
10007,NaN,NaN,NaN,[\n140 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n]
51,"[\n06/2019\n, \n97 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]",NaN,[\n97 g CO2/km (comb)\n],[\nEuro 6\n]
3501,\n08/2019\n,"[\n, \n, \n101 g CO2/km (comb)\n]",NaN,[\n101 g CO2/km (comb)\n],[\nEuro 6\n]
11899,NaN,"[\n, \n, \nEuro 6\n]","[\nYes\n, \n148 g CO2/km (comb)\n]",[\n148 g CO2/km (comb)\n],[\nEuro 6\n]
14055,NaN,NaN,"[\nYes\n, \n120 g CO2/km (comb)\n]",[\n120 g CO2/km (comb)\n],[\nEuro 6\n]
9237,NaN,"[\n, \n, \nEuro 6\n]","[\nYes\n, \n126 g CO2/km (comb)\n]",[\n126 g CO2/km (comb)\n],[\nEuro 6\n]

In [98]:
df.Warranty.isnull().sum()

5420

In [99]:
df.Warranty.value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, \n, \nEuro 6\n]                                                                               1868
\n12 months\n                                                                                      1177
\n                                                                                                  979
\n24 months\n                                                                                       566
[\n, \n, \n4 (Green)\n]                                                                             517
                                                                                                   ...
[\n72 months\n, \n125 g CO2/km (comb)\n]                                                              1
[\n60 months\n, \n14 g CO2/km (comb)\n]                                                               1
[\n24 months\n, \n121 g CO2/km (comb)\n]                                                              1
[\n12 months\n, \nEuro 6d\n]                                                                          1
[\n36 months\n, \n, 7.4 l/100 km (comb), \n, 9.6 l/100 km (city), \n, 6 l/100 km (country), \n]       1
Name: Warranty, Length: 515, dtype: int64

In [95]:
df["Full Service"].unique

<bound method Series.unique of 0                                [\n, \n]
1                                     NaN
2                                     NaN
3        [\n, \n, \n99 g CO2/km (comb)\n]
4                 [\n, \n, \n4 (Green)\n]
                       ...
15914                                 NaN
15915                                 NaN
15916                            [\n, \n]
15917                                 NaN
15918                                 NaN
Name: Full Service, Length: 15919, dtype: object>

In [100]:
df["Full Service"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, \n, \n4 (Green)\n]                                                                       2235
[\n, \n, \nEuro 6\n]                                                                          2097
[\n, \n]                                                                                      1702
[\n, \n, \nEuro 6d-TEMP\n]                                                                     399
\n                                                                                             283
                                                                                              ...
[\n, \n, \n, 6 l/100 km (comb), \n, 8 l/100 km (city), \n, 4.9 l/100 km (country), \n]           1
[\n, \n, \n84 g CO2/km (comb)\n]                                                                 1
[\n, \n, \n87 g CO2/km (comb)\n]                                                                 1
[\n, \n, \n, 5.7 l/100 km (comb), \n, 7.3 l/100 km (city), \n, 4.9 l/100 km (country), \n]       1
[\n, \n, \nEuro 4\n]                                                                             1
Name: Full Service, Length: 122, dtype: int64

In [103]:
df[["Full Service","Warranty","Inspection new", "CO2 Emission", "Emission Class"]].sample(10)

,Full Service,Warranty,Inspection new,CO2 Emission,Emission Class
14558,NaN,NaN,NaN,[\n85 g CO2/km (comb)\n],[\nEuro 6\n]
10143,NaN,"[\n36 months\n, \n150 g CO2/km (comb)\n]","[\nYes\n, \n, 6.6 l/100 km (comb), \n, 8.2 l/1...",[\n150 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n]
9333,"[\n, \n, \n4 (Green)\n]","[\n, \n, \nEuro 6d-TEMP\n]","[\nYes\n, \n140 g CO2/km (comb)\n]",[\n140 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n]
4389,NaN,NaN,NaN,[\n106 g CO2/km (comb)\n],[\nEuro 6\n]
12682,NaN,NaN,NaN,[\n137 g CO2/km (comb)\n],[\nEuro 6\n]
2628,NaN,"[\n, \n, \n119 g CO2/km (comb)\n]",NaN,[\n119 g CO2/km (comb)\n],[\nEuro 6\n]
5819,"[\n, \n, \nEuro 6\n]",NaN,"[\nYes\n, \n122 g CO2/km (comb)\n]",[\n122 g CO2/km (comb)\n],[\nEuro 6\n]
7427,NaN,NaN,NaN,[\n128 g CO2/km (comb)\n],[\nEuro 6\n]
1944,"[\n, \n, \nEuro 6\n]","[\n24 months\n, \n108 g CO2/km (comb)\n]",\nYes\n,[\n108 g CO2/km (comb)\n],[\nEuro 6\n]
9493,"[\n, \n, \nEuro 6\n]",NaN,"[\nYes\n, \n126 g CO2/km (comb)\n]",[\n126 g CO2/km (comb)\n],[\nEuro 6\n]

In [105]:
df[["Full Service","Warranty","Inspection new", "CO2 Emission", "Emission Class","Emission Label"]].sample(10)

,Full Service,Warranty,Inspection new,CO2 Emission,Emission Class,Emission Label
11722,NaN,"[\n, \n, \n142 g CO2/km (comb)\n]",NaN,[\n142 g CO2/km (comb)\n],[\nEuro 6\n],[\n4 (Green)\n]
1468,NaN,\n,NaN,[\n97 g CO2/km (comb)\n],[\nEuro 6\n],[\n1 (No sticker)\n]
14168,NaN,NaN,NaN,[\n85 g CO2/km (comb)\n],[\nEuro 6\n],NaN
4587,NaN,NaN,NaN,[\n117 g CO2/km (comb)\n],[\nEuro 6\n],[\n1 (No sticker)\n]
15764,NaN,"[\n, \n, \n153 g CO2/km (comb)\n]",NaN,[\n153 g CO2/km (comb)\n],[\nEuro 6\n],[\n4 (Green)\n]
2020,NaN,NaN,NaN,[\n111 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n],[\n4 (Green)\n]
5874,"[\n, \n, \n119 g CO2/km (comb)\n]",\n,NaN,[\n119 g CO2/km (comb)\n],[\nEuro 6\n],NaN
341,"[\n, \n, \n104 g CO2/km (comb)\n]",NaN,NaN,[\n104 g CO2/km (comb)\n],[\nEuro 6\n],[\n4 (Green)\n]
7319,"[\n, \n, \nEuro 6\n]","[\n12 months\n, \n133 g CO2/km (comb)\n]",NaN,[\n133 g CO2/km (comb)\n],[\nEuro 6\n],NaN
5059,NaN,NaN,NaN,[\n117 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n],[\n4 (Green)\n]

In [109]:
df["Full Service"].value_counts

<bound method IndexOpsMixin.value_counts of 0                                [\n, \n]
1                                     NaN
2                                     NaN
3        [\n, \n, \n99 g CO2/km (comb)\n]
4                 [\n, \n, \n4 (Green)\n]
                       ...
15914                                 NaN
15915                                 NaN
15916                            [\n, \n]
15917                                 NaN
15918                                 NaN
Name: Full Service, Length: 15919, dtype: object>

In [97]:
df["Full Service"].isnull().sum()

7704

In [106]:
df["Emission Label"].isnull().sum()

11934

In [107]:
df["Emission Label"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n4 (Green)\n]         3553
[\n1 (No sticker)\n]     381
[[], [], []]              40
[\n5 (Blue)\n]             8
[\n3 (Yellow)\n]           2
[\n2 (Red)\n]              1
Name: Emission Label, dtype: int64

In [98]:
df["Non-smoking Vehicle"]

0                       [\n, \n]
1                            NaN
2                            NaN
3           [\n, \n, \nEuro 6\n]
4                       [\n, \n]
                  ...
15914                        NaN
15915    [\n, \n, \n4 (Green)\n]
15916                   [\n, \n]
15917                        NaN
15918                        NaN
Name: Non-smoking Vehicle, Length: 15919, dtype: object

In [100]:
df["Non-smoking Vehicle"].isnull().sum()

8742

In [101]:
df.null.describe()

count     15919
unique        1
top          []
freq      15919
Name: null, dtype: object

In [113]:
df[["Make","Model", "make_model"]].sample(10)

              Make               Model     make_model
1867      \nAudi\n        [\n, A1, \n]        Audi A1
13752  \nRenault\n      [\n, Clio, \n]   Renault Clio
2471      \nAudi\n        [\n, A1, \n]        Audi A1
9753      \nOpel\n     [\n, Corsa, \n]     Opel Corsa
1088      \nAudi\n        [\n, A1, \n]        Audi A1
12963     \nOpel\n  [\n, Insignia, \n]  Opel Insignia
6155      \nOpel\n     [\n, Astra, \n]     Opel Astra
9982      \nOpel\n     [\n, Corsa, \n]     Opel Corsa
14576  \nRenault\n      [\n, Clio, \n]   Renault Clio
162       \nAudi\n        [\n, A1, \n]        Audi A1

In [110]:
df.Make.value_counts()

\nOpel\n       7343
\nAudi\n       5712
\nRenault\n    2864
Name: Make, dtype: int64

In [107]:
df.Make.isnull().sum()

0

In [108]:
df.Make.describe()

count        15919
unique           3
top       \nOpel\n
freq          7343
Name: Make, dtype: object

In [110]:
df.Make.nunique

<bound method IndexOpsMixin.nunique of 0           \nAudi\n
1           \nAudi\n
2           \nAudi\n
3           \nAudi\n
4           \nAudi\n
            ...
15914    \nRenault\n
15915    \nRenault\n
15916    \nRenault\n
15917    \nRenault\n
15918    \nRenault\n
Name: Make, Length: 15919, dtype: object>

In [111]:
df.Make.unique()

array(['\nAudi\n', '\nOpel\n', '\nRenault\n'], dtype=object)

In [116]:
df.Model.unique

<bound method Series.unique of 0            [\n, A1, \n]
1            [\n, A1, \n]
2            [\n, A1, \n]
3            [\n, A1, \n]
4            [\n, A1, \n]
               ...
15914    [\n, Espace, \n]
15915    [\n, Espace, \n]
15916    [\n, Espace, \n]
15917    [\n, Espace, \n]
15918    [\n, Espace, \n]
Name: Model, Length: 15919, dtype: object>

In [117]:
df.Model.nunique

<bound method IndexOpsMixin.nunique of 0            [\n, A1, \n]
1            [\n, A1, \n]
2            [\n, A1, \n]
3            [\n, A1, \n]
4            [\n, A1, \n]
               ...
15914    [\n, Espace, \n]
15915    [\n, Espace, \n]
15916    [\n, Espace, \n]
15917    [\n, Espace, \n]
15918    [\n, Espace, \n]
Name: Model, Length: 15919, dtype: object>

In [118]:
df.Model.isnull().sum()

0

In [114]:
df.Model.value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, A3, \n]          3097
[\n, A1, \n]          2614
[\n, Insignia, \n]    2598
[\n, Astra, \n]       2526
[\n, Corsa, \n]       2219
[\n, Clio, \n]        1839
[\n, Espace, \n]       991
[\n, Duster, \n]        34
[\n, A2, \n]             1
Name: Model, dtype: int64

In [ ]:
Offer Number                      3175
First Registration                1597
Body Color

In [121]:
df["Offer Number"].unique

<bound method Series.unique of 0             [\nLR-062483\n]
1                         NaN
2              [\nAM-95365\n]
3                         NaN
4                 [\nC1626\n]
                 ...
15914          [\n10988301\n]
15915       [\n507370_3223\n]
15916          [\nEspace16\n]
15917           [\n2691331\n]
15918    [\nRe_30000008029\n]
Name: Offer Number, Length: 15919, dtype: object>

In [123]:
df["Offer Number"].isnull().sum()

3175

In [124]:
df["First Registration"].unique #zaten bakmistik bahsettik yukarda

<bound method Series.unique of 0        [\n, 2016, \n]
1        [\n, 2017, \n]
2        [\n, 2016, \n]
3        [\n, 2016, \n]
4        [\n, 2016, \n]
              ...
15914               NaN
15915    [\n, 2019, \n]
15916    [\n, 2019, \n]
15917    [\n, 2019, \n]
15918    [\n, 2019, \n]
Name: First Registration, Length: 15919, dtype: object>

In [115]:
df["First Registration"].isnull().sum()

1597

In [116]:
df["First Registration"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, 2018, \n]    4522
[\n, 2016, \n]    3674
[\n, 2017, \n]    3273
[\n, 2019, \n]    2853
Name: First Registration, dtype: int64

In [128]:
df["Body Color"].unique

<bound method Series.unique of 0        [\n, Black, \n]
1          [\n, Red, \n]
2        [\n, Black, \n]
3        [\n, Brown, \n]
4        [\n, Black, \n]
              ...
15914     [\n, Grey, \n]
15915     [\n, Grey, \n]
15916    [\n, White, \n]
15917     [\n, Grey, \n]
15918     [\n, Grey, \n]
Name: Body Color, Length: 15919, dtype: object>

In [117]:
df["Body Color"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Black, \n]     3745
[\n, Grey, \n]      3505
[\n, White, \n]     3406
[\n, Silver, \n]    1647
[\n, Blue, \n]      1431
[\n, Red, \n]        957
[\n, Brown, \n]      289
[\n, Green, \n]      154
[\n, Beige, \n]      108
[\n, Yellow, \n]      51
[\n, Violet, \n]      18
[\n, Bronze, \n]       6
[\n, Orange, \n]       3
[\n, Gold, \n]         2
Name: Body Color, dtype: int64

In [119]:
df[["Body Color","Body Color Original","Paint Type"]].sample(10)

             Body Color        Body Color Original       Paint Type
3037     [\n, Grey, \n]                        NaN              NaN
2645     [\n, Grey, \n]            [\nAntracite\n]   [\nMetallic\n]
385     [\n, Black, \n]                        NaN   [\nMetallic\n]
9610    [\n, White, \n]               [\nBIANCO\n]  [\nUni/basic\n]
2866    [\n, Black, \n]        [\nMythosschwarz\n]   [\nMetallic\n]
15286    [\n, Grey, \n]        [\nGris Casiopea\n]              NaN
8017    [\n, White, \n]     [\nSchnee Weiß (SL)\n]              NaN
11976  [\n, Silver, \n]          [\nArgonsilber\n]              NaN
5326    [\n, White, \n]            [\nIbisweiss\n]              NaN
3809     [\n, Blue, \n]  [\nkosmosblau metallic\n]   [\nMetallic\n]

In [120]:
df[["Body Color","Body Color Original","Paint Type"]].isnull().sum()

Body Color              597
Body Color Original    3759
Paint Type             5772
dtype: int64

In [128]:
Paint Type                        5772
Body Color Original               3759
Upholstery                        3720
Body                                60
Nr. of Doors                       212
Nr. of Seats

In [129]:
df["Paint Type"].unique

<bound method Series.unique of 0        [\nMetallic\n]
1                   NaN
2        [\nMetallic\n]
3        [\nMetallic\n]
4        [\nMetallic\n]
              ...
15914    [\nMetallic\n]
15915    [\nMetallic\n]
15916               NaN
15917               NaN
15918    [\nMetallic\n]
Name: Paint Type, Length: 15919, dtype: object>

In [131]:
df["Paint Type"].isnull().sum()

5772

In [132]:
df["Paint Type"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\nMetallic\n]       9794
[\nUni/basic\n]       347
[\nPerl effect\n]       6
Name: Paint Type, dtype: int64

In [ ]:
Body Color Original

In [133]:
df["Body Color Original"].isnull().sum()

3759

In [138]:
df["Body Color Original"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\nOnyx Schwarz\n]                     338
[\nBianco\n]                           282
[\nMythosschwarz Metallic\n]           238
[\nBrillantschwarz\n]                  216
[\nGris\n]                             204
                                      ...
[\nRouge-Braun (G0Y)\n]                  1
[\nVARI COLRI DISPONIBILI\n]             1
[\nKokosnussbraun Metallic\n]            1
[\nFarbe frei wählbar\n]                 1
[\nPerlmutt-Weiß Metallic (Weiß)\n]      1
Name: Body Color Original, Length: 1927, dtype: int64

In [139]:
df["Upholstery"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\nCloth, Black\n]           5821
[\nPart leather, Black\n]    1121
[\nCloth\n]                  1005
[\nCloth, Grey\n]             891
[\nCloth, Other\n]            639
[\nFull leather, Black\n]     575
[\nBlack\n]                   491
[\nGrey\n]                    273
[\nOther, Other\n]            182
[\nPart leather\n]            140
[\nFull leather\n]            139
[\nPart leather, Grey\n]      116
[\nFull leather, Brown\n]     116
[\nOther, Black\n]            110
[\nFull leather, Other\n]      72
[\nFull leather, Grey\n]       67
[\nPart leather, Other\n]      65
[\nOther\n]                    56
[\nPart leather, Brown\n]      50
[\nalcantara, Black\n]         47
[\nFull leather, Beige\n]      36
[\nVelour, Black\n]            36
[\nCloth, Brown\n]             28
[\nVelour\n]                   16
[\nOther, Grey\n]              15
[\nCloth, Beige\n]             13
[\nBrown\n]                    12
[\nCloth, Blue\n]              12
[\nCloth, White\n]              8
[\nVelour, Grey\n]              8
[\nalcantara, Grey\n]           6
[\nCloth, Red\n]                5
[\nOther, Yellow\n]             4
[\nBeige\n]                     3
[\nPart leather, Red\n]         3
[\nalcantara\n]                 2
[\nPart leather, White\n]       2
[\nBlue\n]                      2
[\nWhite\n]                     2
[\nPart leather, Beige\n]       2
[\nalcantara, Other\n]          2
[\nFull leather, Blue\n]        2
[\nOther, Brown\n]              1
[\nCloth, Orange\n]             1
[\nFull leather, Red\n]         1
[\nFull leather, White\n]       1
Name: Upholstery, dtype: int64

In [140]:
df["Upholstery"].isnull().sum()

3720

In [ ]:
Body                                60
Nr. of Doors                       212
Nr. of Seats                       977
Model Code

In [143]:
df["Body"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Sedans, \n]           7903
[\n, Station wagon, \n]    3553
[\n, Compact, \n]          3153
[\n, Van, \n]               783
[\n, Other, \n]             290
[\n, Transporter, \n]        88
[\n, Off-Road, \n]           56
[\n, Coupe, \n]              25
[\n, Convertible, \n]         8
Name: Body, dtype: int64

In [144]:
df["Body"].isnull().sum()

60

In [147]:
df["Nr. of Doors"].isnull().sum()

212

In [146]:
df["Nr. of Doors"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n5\n]    11575
[\n4\n]     3079
[\n3\n]      832
[\n2\n]      219
[\n1\n]        1
[\n7\n]        1
Name: Nr. of Doors, dtype: int64

In [149]:
df["Nr. of Seats"].isnull().sum()

977

In [122]:
df["Nr. of Seats"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n5\n]    13336
[\n4\n]     1125
[\n7\n]      362
[\n2\n]      116
[\n6\n]        2
[\n3\n]        1
Name: Nr. of Seats, dtype: int64

In [ ]:
Model Code

In [150]:
df["Model Code"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n0035/BCB\n]    268
[\n0588/BNO\n]    245
[\n0588/BDB\n]    206
[\n0588/BHX\n]    188
[\n1844/ADJ\n]    175
                 ...
[\n0000/ACP\n]      1
[\n0035/BGY\n]      1
[\n0035/bgp\n]      1
[\n0035/BGS\n]      1
[\n3333/BKG\n]      1
Name: Model Code, Length: 232, dtype: int64

In [151]:
df["Model Code"].isnull().sum()

10941

In [ ]:
Gearing Type                         0
Displacement                       496
Cylinders                         5680
Weight                            6974
Drive chain                       6858
Fuel

In [152]:
df["Gearing Type"].isnull().sum()

0

In [153]:
df["Gearing Type"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Manual, \n]            8153
[\n, Automatic, \n]         7297
[\n, Semi-automatic, \n]     469
Name: Gearing Type, dtype: int64

In [154]:
df["Displacement"].isnull().sum()

496

In [155]:
df["Displacement"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n1,598 cc\n]    4761
[\n999 cc\n]      2438
[\n1,398 cc\n]    1314
[\n1,399 cc\n]     749
[\n1,229 cc\n]     677
                  ...
[\n122 cc\n]         1
[\n1,198 cc\n]       1
[\n1,195 cc\n]       1
[\n2,967 cc\n]       1
[\n1,800 cc\n]       1
Name: Displacement, Length: 77, dtype: int64

In [156]:
df.isnull().sum()*100/df.shape[0]

url                                0.000000
make_model                         0.000000
short_description                  0.288963
body_type                          0.376908
price                              0.000000
vat                               28.349771
km                                 0.000000
registration                       0.000000
prev_owner                        42.892141
kW                               100.000000
hp                                 0.000000
Type                               0.012564
Previous Owners                   41.711163
Next Inspection                   77.793831
Inspection new                    75.299956
Warranty                          34.047365
Full Service                      48.395000
Non-smoking Vehicle               54.915510
null                               0.000000
Make                               0.000000
Model                              0.000000
Offer Number                      19.944720
First Registration                10.032037
Body Color                         3.750236
Paint Type                        36.258559
Body Color Original               23.613292
Upholstery                        23.368302
Body                               0.376908
Nr. of Doors                       1.331742
Nr. of Seats                       6.137320
Model Code                        68.729192
Gearing Type                       0.000000
Displacement                       3.115774
Cylinders                         35.680633
Weight                            43.809285
Drive chain                       43.080596
Fuel                               0.000000
Consumption                       11.973114
CO2 Emission                      11.357497
Emission Class                    18.977323
\nComfort & Convenience\n          5.779257
\nEntertainment & Media\n          8.631195
\nExtras\n                        18.606696
\nSafety & Security\n              6.168729
description                        0.000000
Emission Label                    74.967021
Gears                             29.599849
Country version                   52.346253
Electricity consumption           99.139393
Last Service Date                 96.444500
Other Fuel Types                  94.472015
Availability                      96.011056
Last Timing Belt Service Date     99.899491
Available from                    98.291350
dtype: float64

**Missing Value Fonk**

In [13]:
def missing (df):  
    missing_number = df.isnull().sum().sort_values(ascending=False)    
    missing_percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)    
    missing_values = pd.concat([missing_number, missing_percent], axis=1, keys=['Missing_Number', 'Missing_Percent'])
    return missing_values

missing(df)

                               Missing_Number  Missing_Percent
kW                                      15919         1.000000
Last Timing Belt Service Date           15903         0.998995
Electricity consumption                 15782         0.991394
Available from                          15647         0.982913
Last Service Date                       15353         0.964445
Availability                            15284         0.960111
Other Fuel Types                        15039         0.944720
Next Inspection                         12384         0.777938
Inspection new                          11987         0.753000
Emission Label                          11934         0.749670
Model Code                              10941         0.687292
Non-smoking Vehicle                      8742         0.549155
Country version                          8333         0.523463
Full Service                             7704         0.483950
Weight                                   6974         0.438093
Drive chain                              6858         0.430806
prev_owner                               6828         0.428921
Previous Owners                          6640         0.417112
Paint Type                               5772         0.362586
Cylinders                                5680         0.356806
Warranty                                 5420         0.340474
Gears                                    4712         0.295998
vat                                      4513         0.283498
Body Color Original                      3759         0.236133
Upholstery                               3720         0.233683
Offer Number                             3175         0.199447
Emission Class                           3021         0.189773
\nExtras\n                               2962         0.186067
Consumption                              1906         0.119731
CO2 Emission                             1808         0.113575
First Registration                       1597         0.100320
\nEntertainment & Media\n                1374         0.086312
\nSafety & Security\n                     982         0.061687
Nr. of Seats                              977         0.061373
\nComfort & Convenience\n                 920         0.057793
Body Color                                597         0.037502
Displacement                              496         0.031158
Nr. of Doors                              212         0.013317
Body                                       60         0.003769
body_type                                  60         0.003769
short_description                          46         0.002890
Type                                        2         0.000126
Fuel                                        0         0.000000
Gearing Type                                0         0.000000
make_model                                  0         0.000000
Model                                       0         0.000000
Make                                        0         0.000000
description                                 0         0.000000
null                                        0         0.000000
hp                                          0         0.000000
registration                                0         0.000000
km                                          0         0.000000
price                                       0         0.000000
url                                         0         0.000000

In [11]:
df[["make_model","Make","Model"]].sample(15)
#make model diger ikisini bilgilerini icerdigi icin diger ikisi dusurulmelidir

           make_model         Make               Model
3950          Audi A3     \nAudi\n        [\n, A3, \n]
1411          Audi A1     \nAudi\n        [\n, A1, \n]
10726   Opel Insignia     \nOpel\n  [\n, Insignia, \n]
15239  Renault Espace  \nRenault\n    [\n, Espace, \n]
13598    Renault Clio  \nRenault\n      [\n, Clio, \n]
6193       Opel Astra     \nOpel\n     [\n, Astra, \n]
12845   Opel Insignia     \nOpel\n  [\n, Insignia, \n]
10648   Opel Insignia     \nOpel\n  [\n, Insignia, \n]
14186    Renault Clio  \nRenault\n      [\n, Clio, \n]
10878   Opel Insignia     \nOpel\n  [\n, Insignia, \n]
1160          Audi A1     \nAudi\n        [\n, A1, \n]
9520       Opel Corsa     \nOpel\n     [\n, Corsa, \n]
7776       Opel Astra     \nOpel\n     [\n, Astra, \n]
2116          Audi A1     \nAudi\n        [\n, A1, \n]
5606          Audi A3     \nAudi\n        [\n, A3, \n]

In [ ]:
Cylinders                         35.680633
Weight                            43.809285
Drive chain                       43.080596
Fuel                               0.000000
Consumption                       11.973114
CO2 Emission                      11.357497
Emission Class                    18.977323
\nComfort & Convenience\n          5.779257
\nEntertainment & Media\n

In [34]:
df.sample(15).T

,1784,7898,323,5390,2951,1870,5622,2999,11464,365,11753,3043,15817,9244,7792
url,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/opel-astra...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a3-sp...,https://www.autoscout24.com//offers/audi-a3-1-...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a3-sp...,https://www.autoscout24.com//offers/audi-a3-sp...,https://www.autoscout24.com//offers/opel-insig...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/opel-insig...,https://www.autoscout24.com//offers/audi-a3-sp...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/opel-corsa...,https://www.autoscout24.com//offers/opel-astra...
make_model,Audi A1,Opel Astra,Audi A1,Audi A3,Audi A3,Audi A1,Audi A3,Audi A3,Opel Insignia,Audi A1,Opel Insignia,Audi A3,Renault Espace,Opel Corsa,Opel Astra
short_description,Sportback 1.4 TDI design Navi Sportsitze Sitzh.,"K 5-Türer SELECTION 1,0 66kW Klima, IntelliL",1.0 TFSI ultra S-tronic *Navi*Alu*Klima*,Sportback 1.0 TFSI sport MFL SHZG TEMP XENON,1.6 TDI Sportback (clean diesel) S tronic Attract,1.4 TDI 3 porte ultra Sport,"Sportback 30 TFSI Sport Connect,OptikSchwarz",Sportback 1.6 TDI Sport*Doppelbed.*Xen*Navi,1.6 CDTI 136CV Sports Tourer aut. Cosmo Busin,1.4TFSI S-Trc S-Line Sitzh Einpark Bluetooth,2.0 CDTI 170cv Cosmo Business SOLO 7.000km EURO6,"Sportback Sport 1.6 TDI, Navi,Einparkhilfe Plus,S",2.0 dCi In.Paris 7p.,1.4i Enjoy,Sports Tourer 1.4 Turbo BUSINESS EXECUTIVE Sta...
body_type,Sedans,Sedans,Compact,Sedans,Station wagon,Sedans,Sedans,Sedans,Station wagon,Compact,Station wagon,Sedans,Van,Sedans,Station wagon
price,16920,15990,14990,24980,15700,16800,23444,14920,18950,14930,16400,15320,54204,8400,21845
vat,VAT deductible,VAT deductible,VAT deductible,VAT deductible,Price negotiable,VAT deductible,VAT deductible,VAT deductible,None,VAT deductible,VAT deductible,VAT deductible,VAT deductible,Price negotiable,VAT deductible
km,"26,900 km",10 km,"35,367 km","2,890 km","88,000 km","14,500 km","10,000 km","93,307 km","27,850 km","87,300 km","7,000 km","92,067 km",11 km,"30,000 km",- km
registration,06/2018,05/2019,04/2016,03/2019,06/2016,02/2018,02/2019,11/2016,04/2017,07/2016,01/2017,10/2016,05/2019,01/2017,-/-
prev_owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,None,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,None,None,None
kW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hp,66 kW,66 kW,70 kW,85 kW,81 kW,66 kW,85 kW,81 kW,100 kW,92 kW,125 kW,81 kW,146 kW,66 kW,110 kW
Type,"[, Used, , Diesel (Particulate Filter)]","[, Pre-registered, , Super 95 / Regular/Benzin...","[, Used, , Super 95 / Regular/Benzine 91]","[, Used, , Super 95]","[, Used, , Diesel (Particulate Filter)]","[, Employee's car, , Diesel]","[, Used, , Super 95]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Regular/Benzine 91]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, New, , Diesel]","[, Used, , Gasoline]","[, New, , Super E10 95]"
Previous Owners,\n1\n,\n1\n,\n1\n,\n1\n,NaN,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,NaN,NaN,NaN
Next Inspection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[\n06/2021\n, \n99 g CO2/km (comb)\n]",NaN,NaN,NaN
Inspection new,"[\nYes\n, \n102 g CO2/km (comb)\n]","[\nYes\n, \n, 4.7 l/100 km (comb), \n, 5.4 l/1...","[\nYes\n, \n, 4.4 l/100 km (comb), \n, 5.4 l/1...","[\nYes\n, \n114 g CO2/km (comb)\n]",NaN,NaN,"[\nYes\n, \n113 g CO2/km (comb)\n]","[\nYes\n, \n0 kWh/100 km (comb)\n]",NaN,"[\nYes\n, \n112 g CO2/km (comb)\n]",NaN,"[\nYes\n, \nEuro 6\n]",NaN,NaN,"[\nYes\n, \n130 g CO2/km (comb)\n]"
Warranty,"[\n, \n, \nEuro 6\n]","[\n72 months\n, \n107 g CO2/km (comb)\n]","[\n12 months\n, \n102 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]",NaN,"[\n, \n, \n89 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]","[\n12 months\n, \n99 g CO2/km (comb)\n]","[\n, \n, \n132 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]","[\n12 months\n, \n119 g CO2/km (comb)\n]","[\n, \n, \n4 (Green)\n]",NaN,NaN,NaN
Full Service,"[\n, \n, \n4 (Green)\n]","[\n, \n, \nEuro 6d-TEMP\n]",NaN,"[\n, \n, \n4 (Green)\n]",NaN,NaN,"[\n, \n, \n4 (Green)\n]","[\n, \n, \nEuro 6\n]",NaN,"[\n, \n, \n4 (Green)\n]","[\n, \n, \nEuro 6\n]","[\n, \n]",\n,NaN,NaN
Non-smoking Vehicle,"[\n, \n]","[\n, \n]","[\n, \n, \nEuro 6\n]","[\n, \n]",NaN,"[\n, \n, \nEuro 6\n]","[\n, \n]","[\n, \n, \n4 (Green)\n]",NaN,"[\n, \n]",NaN,"[\n, \n]",NaN,NaN,"[\n, \n, \nEuro 6d-TEMP\n]"
null,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
Make,\nAudi\n,\nOpel\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nOpel\n,\nAudi\n,\nOpel\n,\nAudi\n,\nRenault\n,\nOpel\n,\nOpel\n
Model,"[\n, A1, \n]","[\n, Astra, \n]","[\n, A1, \n]","[\n, A3, \n]","[\n, A3, \n]","[\n, A1, \n]","[\n, A3, \n]","[\n, A3, \n]","[\n, Insignia, \n]","[\n, A1, \n]","[\n, Insignia, \n]","[\n, A3, \n]","[\n, Espace, \n]","[\n, Corsa, \n]","[\n, Astra, \n]"
Offer Number,[\n19633P33\n],[\nG364074\n],[\nGW103265\n],[\nA139900\n],NaN,[\nA001\n],[\nEG-GEU344\n],[\nHBS2302\n],[\n1515727\n],[\n09-93727\n],[\n2448524\n],[\n4483\n],[\n35615\n],NaN,[\n68414\n]
First Registration,"[\n, 2018, \n]","[\n, 2019, \n]","[\n, 2016, \n]","[\n, 2019, \n]","[\n, 2016, \n]","[\n, 2018, \n]","[\n, 2019, \n]","[\n, 2016, \n]","[\n, 2017, \n]","[\n, 2016, \n]","[\n, 2017, \n]","[\n, 2016, \n]","[\n, 2019, \n]","[\n, 2017, \n]",NaN
Body Color,"[\n, Red, \n]","[\n, Grey, \n]","[\n, Blue, \n]","[\n, Black, \n]","[\n, Silver, \n]","[\n, Black, \n]","[\n, White, \n]","[\n, Silver, \n]","[\n, Grey, \n]","[\n, Black, \n]","[\n, Silver, \n]","[\n, Black, \n]","[\n, White, \n]","[\n, Grey, \n]",NaN
Paint Type,[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],NaN,[\nMetallic\n],NaN,[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],NaN,NaN
Body Color Original,[\nMisanorot Perleffekt\n],[\nQuarz Grau\n],[\nblau\n],[\nMythosschwarz Metallic\n],NaN,NaN,[\nIbisweiß\n],[\nFlorettsilber Metallic\n],[\nSHINY ROCK MET.\n],[\nMythosschwarz Metallic\n],[\nArgento\n],[\nMythosschwarz\n],[\nWit\n],NaN,[\nwählbar - ggf. mit Aufpreis\n]
Upholstery,"[\nCloth, Black\n]","[\nCloth, Black\n]","[\nCloth, Black\n]","[\nCloth, Black\n]","[\nCloth, Grey\n]","[\nCloth, Black\n]","[\nCloth, Black\n]","[\nCloth, Black\n]",NaN,"[\nCloth, Black\n]","[\nPart leather, Black\n]","[\nCloth, Black\n]",[\nPart leather\n],NaN,"[\nCloth, Other\n]"
Body,"[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Compact, \n]","[\n, Sedans, \n]","[\n, Station wagon, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Station wagon, \n]","[\n, Compact, \n]","[\n, Station wagon, \n]","[\n, Sedans, \n]","[\n, Van, \n]","[\n, Sedans, \n]","[\n, Station wagon, \n]"
Nr. of Doors,[\n4\n],[\n5\n],[\n3\n],[\n5\n],[\n5\n],[\n3\n],[\n5\n],[\n4\n],[\n5\n],[\n3\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n]
Nr. of Seats,[\n5\n],[\n5\n],[\n4\n],[\n5\n],[\n5\n],[\n4\n],[\n5\n],[\n5\n],[\n5\n],[\n4\n],[\n5\n],[\n5\n],NaN,[\n5\n],[\n5\n]
Model Code,NaN,NaN,NaN,[\n0588/BHX\n],[\n0588/AYB\n],NaN,[\n0588/BHX\n],[\n0588/AYB\n],NaN,[\n0588/BCW\n],NaN,[\n0588/AYB\n],NaN,NaN,NaN
Gearing Type,"[\n, Manual, \n]","[\n, Manual, \n]","[\n, Automatic, \n]","[\n, Manual, \n]","[\n, Automatic, \n]","[\n, Manual, \n]","[\n, Manual, \n]","[\n, Manual, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Manual, \n]","[\n, Manual, \n]","[\n, Automatic, \n]","[\n, Manual, \n]","[\n, Automatic, \n]"
Displacement,"[\n1,422 cc\n]",[\n998 cc\n],[\n999 cc\n],[\n999 cc\n],"[\n1,598 cc\n]","[\n1,422 cc\n]",[\n999 cc\n],"[\n1,598 cc\n]","[\n1,598 cc\n]","[\n1,395 cc\n]","[\n1,956 cc\n]","[\n1,598 cc\n]","[\n1,997 cc\n]","[\n1,398 cc\n]","[\n1,398 cc\n]"
Cylinders,NaN,NaN,NaN,[\n3\n],[\n4\n],[\n3\n],NaN,[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n]
Weight,NaN,NaN,NaN,"[\n1,255 kg\n]","[\n1,355 kg\n]","[\n1,120 kg\n]","[\n1,255 kg\n]",NaN,"[\n2,270 kg\n]",NaN,"[\n1,658 kg\n]","[\n1,350 kg\n]","[\n1,779 kg\n]","[\n1,163 kg\n]","[\n1,350 kg\n]"
Drive chain,NaN,NaN,NaN,[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],NaN,NaN,[\nfront\n]
Fuel,"[\n, Diesel (Particulate Filter), \n]","[\n, Super 95 / Regular/Benzine 91, \n]","[\n, Super 95 / Regular/Benzine 91, \n]","[\n, Super 95, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel, \n]","[\n, Super 95, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Regular/Benzine 91, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel, \n]","[\n, Gasoline, \n]","[\n, Super E10 95, \n]"
Consumption,"[[3.9 l/100 km (comb)], [4.5 l/100 km (city)],...","[\n, 4.7 l/100 km (comb), \n, 5.4 l/100 km (ci...","[\n, 4.4 l/100 km (comb), \n, 5.4 l/100 km (ci...","[[4.8 l/100 km (comb)], [5.8 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[3.4 l/100 km (comb)], [3.9 l/100 km (city)],...","[[4.8 l/100 km (comb)], [5.8 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[5 l/100 km (comb)], [6.5 l/100 km (city)], [...","[[4.9 l/100 km (comb)], [6.2 l/100 km (city)],...","[[4.5 l/100 km (comb)], [5.7 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[5.4 l/100 km (comb)], [6.3 l/100 km (city)],...","[[5.2 l/100 km (comb)], [6.8 l/100 km (city)],...","[[5.7 l/100 km (comb)], [7.3 l/100 km (city)],..."
CO2 Emission,[\n102 g CO2/km (comb)\n],[\n107 g CO2/km (comb)\n],[\n102 g CO2/km (comb)\n],[\n114 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n89 g CO2/km (comb)\n],[\n113 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n132 g CO2/km (comb)\n],[\n112 g CO2/km (comb)\n],[\n119 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],NaN,[\n120 g CO2/km (comb)\n],[\n130 g CO2/km (comb)\n]
Emission Class,[\nEuro 6\n],NaN,NaN,[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],NaN,[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],NaN,[\nEuro 6\n],[\nEuro 6d-TEMP\n]
\nComfort & Convenience\n,"[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Cruise control, Electrical ...","[Air conditioning, Electrical side mirrors, Hi...","[Air conditioning, Cruise control, Multi-funct...","[Air conditioning, Armrest, Cruise control, Hi...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Armrest, Cruise control, El...","[Air conditioning, Cruise control, Electrical ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Armrest, Electrical side mi...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Electrical side mirrors, Na...","[Air conditioning, Armrest, Automatic climate ...","[Electrical side mirrors, Power windows]","[Air conditioning, Armrest, Automatic climate ..."
\nEntertainment & Media\n,"[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, CD player, Hands-free equipment, M...","[On-board computer, Radio]","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, Radio]","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, R...","[Digital radio, Radio]","[Bluetooth, CD player, On-board computer, USB]","[Bluetooth, Digital radio, On-board computer, ..."
\nExtras\n,"[Alloy wheels, Sport seats]",NaN,[Alloy wheels],"[Alloy wheels, Sport seats, Sport suspension]","[Sport suspension, Trailer hitch, Voice Control]","[Alloy wheels, Sport seats]","[Alloy wheels, Cab or rented Car, Sport seats,...",[Alloy wheels],[Alloy wheels],"[Alloy wheels, Catalytic Converter, Shift padd...","[Alloy wheels, Catalytic Converter, Roof rack]","[Alloy wheels, Roof rack]","[Alloy wheels, Voice Control]",NaN,"[Catalytic Converter, Roof rack, Touch screen]"
\nSafety & Security\n,"[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light...","[ABS, Adaptive headlights, Central door lock w...","[ABS, Adaptive headlights, Alarm system, Centr...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Central door lock wit...","[ABS, Central door lock, Driver-side airbag, E...","[ABS, Central door lock, Daytime running light...","[ABS, Alarm system, Central door lock, Central...","[ABS, Central door lock, Daytime running light...","[ABS, Daytime running lights, Driver-side airb...","[ABS, Central door lock with remote control, D...","[Central door lock, Daytime running lights, Dr..."
description,"[\n, 6XD Außenspiegel beheizbar, 8N6 Licht-/Re...","[\n, Klimaanlage, Start/Stop-Automatik, Blueto...","[\n, Klimaanlage, Navigation, Euronorm 6 (Umwe...","[\n, Highlights, , Sitzheizung vorne, , Xeno...","[\nHallo,, bieten meinen Audi A3 aus dem Jahr ...",[\nAUTO AZIENDALE TENUTA IN CONDIZIONI PARI AL...,"[\n, Highlights: , Qualitätssiegel GW:plus, An...","[\n, Highlights: , 1. Hand; Scheckheftgepflegt...","[\nAuto aziendale completa di Navig. Satell, C...","[\n, Technik & Sicherheit:, Nebelscheinwerfer,...","[\nDEK:[2448524], Telaio: W0LGT8E16G1058123, O...","[\n, Änderungen, Zwischenverkauf und Irrtümer ...",[\nDe geadverteerde prijs is een vaste prijs z...,"[\nOpel Corsa 1.4i – 90pk - 30000km, Eerste in...","[\n, , Neues Fahrzeug inkl.19% MWST, Fahrzeug..."
Emission Label,NaN,NaN,[\n4 (Green)\n],NaN,[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[\n4 (Green)\n]
Gears,NaN,[\n5\n],NaN,[\n6\n],[\n7\n],[\n5\n],NaN,[\n6\n],[\n6\n],NaN,[\n6\n],[\n6\n],[\n3\n],[\n5\n],[\n6\n]
Country version,[\nGermany\n],[\nGermany\n],[\nGermany\n],NaN,NaN,[\nItaly\n],[\nGermany\n],[\nGermany\n],NaN,[\nGermany\n],[\nItaly\n],NaN,[\nNetherlands\n],NaN,[\nNetherlands\n]
Electricity consumption,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[\n0 kWh/100 km (comb)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last Service Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Other Fuel Types,NaN,"[[], [], []]","[[], [], []]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Availability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\nin 90 days from ordering\n
Last Timing Belt Service Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Available from,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
df["Cylinders"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n4\n]    8105
[\n3\n]    2104
[\n5\n]      22
[\n6\n]       3
[\n8\n]       2
[\n2\n]       2
[\n1\n]       1
Name: Cylinders, dtype: int64

In [124]:
df["Cylinders"].isnull().sum()

5680

In [126]:
df["Weight"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n1,163 kg\n]    574
[\n1,360 kg\n]    356
[\n1,165 kg\n]    301
[\n1,335 kg\n]    242
[\n1,135 kg\n]    213
                 ...
[\n1,331 kg\n]      1
[\n1,132 kg\n]      1
[\n1,252 kg\n]      1
[\n1,792 kg\n]      1
[\n2,037 kg\n]      1
Name: Weight, Length: 434, dtype: int64

In [128]:
df["Weight"].isnull().sum()

6974

In [129]:
df["Drive chain"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\nfront\n]    8886
[\n4WD\n]       171
[\nrear\n]        4
Name: Drive chain, dtype: int64

In [130]:
df["Drive chain"].isnull().sum()

6858

In [6]:
df

NameError: ignored

In [11]:
df["Fuel"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n, Diesel (Particulate Filter), \n]                                                                                  4315
[\n, Super 95, \n]                                                                                                     3338
[\n, Gasoline, \n]                                                                                                     3175
[\n, Diesel, \n]                                                                                                       2984
[\n, Super 95 / Regular/Benzine 91, \n]                                                                                 424
                                                                                                                       ...
[\n, Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91, \n]                                                          1
[\n, Super Plus 98 / Super E10 95, \n]                                                                                    1
[\n, Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98, \n]       1
[\n, Regular/Benzine 91 / Super Plus 98 / Regular/Benzine E10 91 / Super 95 / Super E10 95 / Super Plus E10 98, \n]       1
[\n, Super Plus 98 / Super 95 / Super Plus E10 98, \n]                                                                    1
Name: Fuel, Length: 77, dtype: int64

In [12]:
df["Fuel"].isnull().sum()

0

In [13]:
df["Consumption"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[[3.9 l/100 km (comb)], [4.1 l/100 km (city)], [3.7 l/100 km (country)]]              304
[[4.2 l/100 km (comb)], [5 l/100 km (city)], [3.7 l/100 km (country)]]                276
[[5.4 l/100 km (comb)], [6.8 l/100 km (city)], [4.5 l/100 km (country)]]              257
[[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]              253
[[4.7 l/100 km (comb)], [5.1 l/100 km (city)], [4.4 l/100 km (country)]]              244
                                                                                     ...
[[4.2 l/100 km (comb)], [5.3 l/100 km (city)], [3.6 l/100 km (country)]]                1
[\n, 5.1 l/100 km (comb), \n, 6.4 l/100 km (city), \n, 4.3 l/100 km (country), \n]      1
[[4.6 l/100 km (comb)], [5.4 l/100 km (city)], [6.7 l/100 km (country)]]                1
[\n, 6.3 l/100 km (comb), \n, \n, \n]                                                   1
[\n, 7.4 l/100 km (comb), \n, 9.6 l/100 km (city), \n, 6 l/100 km (country), \n]        1
Name: Consumption, Length: 881, dtype: int64

In [14]:
df["Consumption"].isnull().sum()

1906

In [19]:
df[["Full Service","Warranty","Inspection new", "CO2 Emission", "Emission Class","Emission Label","Consumption"]].sample(10)#baglantili cikmadi

,Full Service,Warranty,Inspection new,CO2 Emission,Emission Class,Emission Label,Consumption
8910,"[\n, \n]",[\n12 months\n],"[\nYes\n, \nEuro 6\n]",[\n90 g CO2/km (comb)\n],[\nEuro 6\n],NaN,"[[3.4 l/100 km (comb)], [3.9 l/100 km (city)],..."
6527,NaN,"[\n12 months\n, \n104 g CO2/km (comb)\n]",NaN,[\n104 g CO2/km (comb)\n],[\nEuro 6\n],NaN,"[[5.5 l/100 km (comb)], [], []]"
11088,"[\n, \n, \n109 g CO2/km (comb)\n]",NaN,NaN,[\n109 g CO2/km (comb)\n],[\nEuro 6\n],NaN,"[[3.6 l/100 km (comb)], [5 l/100 km (city)], [..."
9738,NaN,NaN,NaN,[\n123 g CO2/km (comb)\n],[\nEuro 6c\n],[\n4 (Green)\n],"[[5.2 l/100 km (comb)], [6.6 l/100 km (city)],..."
3001,"[\n, \n]","[\n, \n, \n4 (Green)\n]","[\nYes\n, \nEuro 6\n]",[\n99 g CO2/km (comb)\n],[\nEuro 6\n],NaN,"[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],..."
11271,NaN,\n12 months\n,NaN,[\n109 g CO2/km (comb)\n],[\nEuro 6\n],NaN,"[[4.1 l/100 km (comb)], [4.8 l/100 km (city)],..."
13889,"[\n, \n, \n130 g CO2/km (comb)\n]",NaN,NaN,[\n130 g CO2/km (comb)\n],[\nEuro 6\n],[\n4 (Green)\n],"[[5.7 l/100 km (comb)], [7.2 l/100 km (city)],..."
15405,"[\n, \n, \n120 g CO2/km (comb)\n]",NaN,NaN,[\n120 g CO2/km (comb)\n],[\nEuro 6\n],NaN,"[[4.7 l/100 km (comb)], [5.1 l/100 km (city)],..."
14660,"[\n, \n, \n4 (Green)\n]","[\n, \n, \nEuro 6\n]",NaN,[\n113 g CO2/km (comb)\n],[\nEuro 6\n],NaN,"[[5 l/100 km (comb)], [6.3 l/100 km (city)], [..."
13403,NaN,NaN,NaN,"[[], [], []]",[\nEuro 6\n],NaN,NaN

In [21]:
df[["Cylinders","Consumption"]].sample()

     Cylinders                                        Consumption
3032   [\n4\n]  [[], [3.4 l/100 km (city)], [3.8 l/100 km (cou...

In [23]:
df["Co2 emission"].isnull().sum()

KeyError: ignored

In [24]:
df["\nComfort & Convenience\n"].value_counts()

KeyError: ignored

In [29]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,15909,15910,15911,15912,15913,15914,15915,15916,15917,15918
url,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-1-...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-sp...,https://www.autoscout24.com//offers/audi-a1-sp...,...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...,https://www.autoscout24.com//offers/renault-es...
make_model,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,...,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace
short_description,Sportback 1.4 TDI S-tronic Xenon Navi Klima,1.8 TFSI sport,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,1.4 TDi Design S tronic,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,1.6 TDI Sport DSG *SHZ*Xenon*Navi*Bose*PDC*,Sportback 1.6 TDI S-TRONIC S-LINE*NAVI|XENON*,Sportback 1.4 TDI admired S tronic,SPB 1.6 TDI S-tronic Metal plus + Xeno,SPORTBACK TFSI ULTRA 95 S-TRONIC AMB.,...,Limited Blue dCi 200 EDC,TCe 225 EDC INITIALE PDC SHZ BOSE KLIMA,ELYSEE ENERGY dCi 160 EDC,Blue dCi 200CV EDC Executive 4Control,INITIALE Paris TCe 225 EDC GPF ACC EU6,Blue dCi 200CV EDC Executive 4Control,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Blue dCi 200 EDC Initiale Paris Leder LED Navi...,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX
body_type,Sedans,Sedans,Sedans,Sedans,Sedans,Sedans,Station wagon,Compact,Sedans,Sedans,...,Van,Van,Van,Van,Van,Van,Van,Van,Van,Van
price,15770,14500,14640,14500,16790,15090,16422,14480,16700,17990,...,39990,39980,39980,39950,39950,39950,39885,39875,39700,40999
vat,VAT deductible,Price negotiable,VAT deductible,None,None,None,VAT deductible,VAT deductible,None,None,...,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible
km,"56,013 km","80,000 km","83,450 km","73,000 km","16,200 km","63,668 km","62,111 km","14,986 km","57,000 km","16,103 km",...,"3,500 km","8,500 km",100 km,- km,"1,000 km",- km,"9,900 km",15 km,10 km,- km
registration,01/2016,03/2017,02/2016,08/2016,05/2016,02/2016,03/2016,02/2016,02/2016,06/2017,...,05/2019,02/2019,02/2019,-/-,04/2019,-/-,01/2019,03/2019,06/2019,01/2019
prev_owner,2 previous owners,None,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,1 previous owner,None,...,None,1 previous owner,1 previous owner,None,None,None,1 previous owner,1 previous owner,None,1 previous owner
kW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hp,66 kW,141 kW,85 kW,66 kW,66 kW,85 kW,85 kW,66 kW,85 kW,70 kW,...,147 kW,165 kW,118 kW,147 kW,165 kW,147 kW,165 kW,146 kW,147 kW,165 kW
Type,"[, Used, , Diesel (Particulate Filter)]","[, Used, , Gasoline]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Diesel (Particulate Filter)]","[, Used, , Gasoline]",...,"[, Demonstration, , Diesel (Particulate Filter)]","[, Demonstration, , Regular/Benzine E10 91]","[, Pre-registered, , Diesel (Particulate Filter)]","[, New, , Diesel (Particulate Filter)]","[, Demonstration, , Super 95]","[, New, , Diesel (Particulate Filter)]","[, Used, , Super 95 / Super Plus 98 (Particula...","[, Pre-registered, , Diesel]","[, Pre-registered, , Diesel]","[, Demonstration, , Super 95]"
Previous Owners,\n2\n,NaN,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,\n1\n,NaN,...,NaN,\n1\n,\n1\n,NaN,NaN,NaN,"[\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100...","[\n1\n, \n139 g CO2/km (comb)\n]",NaN,\n1\n
Next Inspection,"[\n06/2021\n, \n99 g CO2/km (comb)\n]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[\n02/2020\n, \n97 g CO2/km (comb)\n]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[\n01/2022\n, \n168 g CO2/km (comb)\n]",NaN,NaN,NaN
Inspection new,"[\nYes\n, \nEuro 6\n]",NaN,NaN,NaN,"[\nYes\n, \n109 g CO2/km (comb)\n]",NaN,"[\nYes\n, \n98 g CO2/km (comb)\n]","[\nYes\n, \n97 g CO2/km (comb)\n]",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[\nYes\n, \nEuro 6d-TEMP\n]",NaN,"[\nYes\n, \n153 g CO2/km (comb)\n]"
Warranty,"[\n, \n, \n4 (Green)\n]",NaN,"[\n, \n, \n99 g CO2/km (comb)\n]",NaN,"[\n, \n, \nEuro 6\n]",NaN,NaN,"[\n, \n, \nEuro 6\n]","[\n12 months\n, \nEuro 6\n]",\n3 months\n,...,\n48 months\n,NaN,NaN,\n24 months\n,NaN,\n24 months\n,"[\n, \n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]",\n,NaN
Full Service,"[\n, \n]",NaN,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]","[\n, \n, \n4 (Green)\n]","[\n, \n, \n92 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]",NaN,NaN,...,NaN,"[\n, \n, \n153 g CO2/km (comb)\n]",NaN,NaN,NaN,NaN,NaN,"[\n, \n]",NaN,NaN
Non-smoking Vehicle,"[\n, \n]",NaN,NaN,"[\n, \n, \nEuro 6\n]","[\n, \n]","[\n, \n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]",NaN,NaN,NaN,...,NaN,"[\n, \n, \nEuro 6\n]","[\n, \n, \n123 g CO2/km (comb)\n]",NaN,NaN,NaN,"[\n, \n, \n4 (Green)\n]","[\n, \n]",NaN,NaN
null,[],[],[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],[]
Make,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,\nAudi\n,...,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n,\nRenault\n
Model,"[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]","[\n, A1, \n]",...,"[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]","[\n, Espace, \n]"
Offer Number,[\nLR-062483\n],NaN,[\nAM-95365\n],NaN,[\nC1626\n],[\nJV03654\n],[\n200-19\n],[\n18381A-Q2\n],[\n11540324\n],NaN,...,[\n1-15447\n],[\n1720LR8\n],[\nVB1_12468\n],[\n10988276\n],[\nNW9766\n],[\n10988301\n],[\n507370_3223\n],[\nEspace16\n],[\n2691331\n],[\nRe_30000008029\n]
First Registration,"[\n, 2016, \n]","[\n, 2017, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2016, \n]","[\n, 2017, \n]",...,"[\n, 2019, \n]","[\n, 2019, \n]","[\n, 2019, \n]",NaN,"[\n, 2019, \n]",NaN,"[\n, 2019, \n]","[\n, 2019, \n]","[\n, 2019, \n]","[\n, 2019, \n]"
Body Color,"[\n, Black, \n]","[\n, Red, \n]","[\n, Black, \n]","[\n, Brown, \n]","[\n, Black, \n]","[\n, White, \n]","[\n, White, \n]","[\n, Red, \n]","[\n, Grey, \n]","[\n, White, \n]",...,"[\n, Black, \n]","[\n, Blue, \n]","[\n, White, \n]","[\n, Black, \n]","[\n, White, \n]","[\n, Grey, \n]","[\n, Grey, \n]","[\n, White, \n]","[\n, Grey, \n]","[\n, Grey, \n]"
Paint Type,[\nMetallic\n],NaN,[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],NaN,...,[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],[\nMetallic\n],NaN,NaN,[\nMetallic\n]
Body Color Original,[\nMythosschwarz\n],NaN,[\nmythosschwarz metallic\n],NaN,[\nMythosschwarz Metallic\n],NaN,[\nGletscherweiss\n],[\nMisanorot Perleffekt\n],[\nGrigio\n],[\nBlanc\n],...,[\nBlack-Pearl\n],[\nKosmos-Blau\n],[\nPerlmutt-Weiß Metallic (Weiß)\n],[\nNero\n],[\nperlmutt-weiss\n],[\nGrigio scuro\n],[\nStahl-Grau Metallic\n],[\narktis-weiß\n],[\nGrigio\n],[\nTitanium-Grau Metallic\n]
Upholstery,"[\nCloth, Black\n]","[\nCloth, Grey\n]","[\nCloth, Black\n]",NaN,"[\nCloth, Black\n]","[\nPart leather, Black\n]","[\nPart leather, Black\n]","[\nCloth, Black\n]","[\nCloth, Grey\n]",NaN,...,NaN,"[\nFull leather, Other\n]","[\nFull leather, Grey\n]",NaN,"[\nFull leather, Brown\n]",NaN,[\nCloth\n],"[\nFull leather, Black\n]",[\nPart leather\n],"[\nFull leather, Brown\n]"
Body,"[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]","[\n, Station wagon, \n]","[\n, Compact, \n]","[\n, Sedans, \n]","[\n, Sedans, \n]",...,"[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]","[\n, Van, \n]"
Nr. of Doors,[\n5\n],[\n3\n],[\n4\n],[\n3\n],[\n5\n],[\n4\n],[\n4\n],[\n5\n],[\n5\n],[\n5\n],...,[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n]
Nr. of Seats,[\n5\n],[\n4\n],[\n4\n],[\n4\n],[\n5\n],[\n5\n],[\n5\n],[\n5\n],[\n4\n],[\n4\n],...,[\n5\n],[\n5\n],[\n7\n],[\n5\n],[\n7\n],[\n5\n],[\n5\n],[\n7\n],[\n7\n],[\n5\n]
Model Code,[\n0588/BDF\n],[\n0588/BCY\n],NaN,NaN,[\n0588/BDF\n],NaN,NaN,[\n0588/BDF\n],NaN,NaN,...,NaN,[\n3333/BHJ\n],[\n3333/BDQ\n],NaN,NaN,NaN,[\n0000/000\n],NaN,NaN,[\n3333/BHJ\n]
Gearing Type,"[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]",...,"[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]","[\n, Automatic, \n]"
Displacement,"[\n1,422 cc\n]","[\n1,798 cc\n]","[\n1,598 cc\n]","[\n1,422 cc\n]","[\n1,422 cc\n]","[\n1,598 cc\n]","[\n1,598 cc\n]","[\n1,422 cc\n]","[\n1,598 cc\n]",[\n999 cc\n],...,"[\n1,997 cc\n]","[\n1,798 cc\n]","[\n1,598 cc\n]","[\n1,997 cc\n]","[\n1,798 cc\n]","[\n1,997 cc\n]","[\n1,798 cc\n]","[\n1,997 cc\n]","[\n1,997 cc\n]","[\n1,798 cc\n]"
Cylinders,[\n3\n],[\n4\n],NaN,[\n3\n],[\n3\n],NaN,[\n4\n],NaN,[\n4\n],NaN,...,NaN,[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n],[\n4\n]
Weight,"[\n1,220 kg\n]","[\n1,255 kg\n]",NaN,"[\n1,195 kg\n]",NaN,NaN,NaN,NaN,"[\n1,275 kg\n]",NaN,...,"[\n1,779 kg\n]",NaN,"[\n1,734 kg\n]","[\n1,758 kg\n]",NaN,"[\n1,758 kg\n]","[\n1,708 kg\n]",NaN,"[\n1,758 kg\n]","[\n1,685 kg\n]"
Drive chain,[\nfront\n],[\nfront\n],[\nfront\n],NaN,[\nfront\n],NaN,[\nfront\n],[\nfront\n],[\nfront\n],NaN,...,NaN,[\nfront\n],NaN,[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\nfront\n],[\n4WD\n]
Fuel,"[\n, Diesel (Particulate Filter), \n]","[\n, Gasoline, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Gasoline, \n]",...,"[\n, Diesel (Particulate Filter), \n]","[\n, Regular/Benzine E10 91, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Super 95, \n]","[\n, Diesel (Particulate Filter), \n]","[\n, Super 95 / Super Plus 98 (Particulate Fil...","[\n, Diesel, \n]","[\n, Diesel, \n]","[\n, Super 95, \n]"
Consumption,"[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[5.6 l/100 km (comb)], [7.1 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.4 l/100 km (city)],...","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...","[[4.1 l/100 km (comb)], [4.6 l/100 km (city)],...","[[3.5 l/100 km (comb)], [4.3 l/100 km (city)],...","[[3.7 l/100 km (comb)], [4.3 l/100 km (city)],...","[[3.7 l/100 km (comb)], [4.2 l/100 km (city)],...","[[3.7 l/100 km (comb)], [4.3 l/100 km (city)],...",NaN,...,NaN,"[[6 l/100 km (comb)], [8 l/100 km (city)], [5 ...","[[4.7 l/100 km (comb)], [5.1 l/100 km (city)],...","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...","[[6.8 l/100 km (comb)], [8.7 l/100 km (city)],...","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...","[\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (ci...","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...","[[6.8 l/100 km (comb)], [8.7 l/100 km (city)],..."
CO2 Emission,[\n99 g CO2/km (comb)\n],[\n129 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n99 g CO2/km (comb)\n],[\n109 g CO2/km (comb)\n],[\n92 g CO2/km (comb)\n],[\n98 g CO2/km (comb)\n],[\n97 g CO2/km (comb)\n],[\n97 g CO2/km (comb)\n],NaN,...,"[[], [], []]",[\n153 g CO2/km (comb)\n],[\n123 g CO2/km (comb)\n],[\n139 g CO2/km (comb)\n],[\n153 g CO2/km (comb)\n],[\n139 g CO2/km (comb)\n],[\n168 g CO2/km (comb)\n],[\n139 g CO2/km (comb)\n],[\n139 g CO2/km (comb)\n],[\n153 g CO2/km (comb)\n]
Emission Class,[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],[\nEuro 6\n],NaN,...,NaN,[\nEuro 6\n],[\nEuro 6\n],NaN,[\nEuro 6\n],NaN,NaN,[\nEuro 6d-TEMP\n],[\nEuro 6\n],[\nEuro 6\n]
\nComfort & Convenience\n,"[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Cruise control, Electrical ...","[Air suspension, Armrest, Auxiliary heating, E...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Armrest, Electrical side mi...","[Air conditioning, Power windows]",NaN,...,"[Air conditioning, Automatic climate control, ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Armrest, Automatic climate ...","[Air conditioning, Automatic climate control, ...","[Air conditioning, Automatic climate control, ..."
\nEntertainment & Media\n,"[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Hands-free equipment, On-board com...","[MP3, On-board computer]","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, CD player, Hands-free equipment, M...","[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, CD player, Hands-free equipment, O...","[CD player, MP3, Radio]",[Radio],NaN,...,"[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Digital radio, Hands-free equipmen...","[Bluetooth, Hands-free equipment, On-board com...","[Bluetooth, Digital radio, Radio, USB]",[USB]
\nExtras\n,"[Alloy wheels, Catalytic Converter, Voice Cont...","[Alloy wheels, Sport seats, Sport suspension, ...","[Alloy wheels, Voice Control]","[Alloy wheels, Sport seats, Voice Control]","[Alloy wheels, Sport package, Sport suspension...","[Alloy wheels, Sport package, Sport seats, Spo...","[Alloy wheels, Sport package, Sport seats, Spo...",[Alloy wheels],[Alloy wheels],NaN,...,"[Alloy wheels, Touch screen]",[Alloy wheels],"[Alloy wheels, Touch screen, Voice Control]","[Alloy wheels, Touch screen]","[Alloy wheels, Catalytic Converter, Sport susp...","[Alloy wheels, Touch screen]","[Alloy wheels, Touch screen, Voice Control]",[Alloy wheels],"[Alloy wheels, Touch screen]","[Alloy wheels, Touch screen]"
\nSafety & Security\n,"[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Central door lock wit...","[ABS, Central door lock, Daytime running light...","[ABS, Alarm system, Central door lock with rem...","[ABS, Central door lock, Driver-side airbag, E...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Daytime running light...","[ABS, Central door lock, Driver-side airbag, E...",NaN,...,"[ABS, Blind spot monitor, Central door lock, D...","[ABS, Adaptive headlights, Central door lock, ...","[ABS, Adaptive Cruise Control, Central door lo...","[ABS, Central door lock, Central door lock wit...","[ABS, Adaptive Cruise Control, Blind spot moni...","[ABS, Central door lock, Central door lock wit...","[ABS, Adaptive Cruise Control, Blind spot moni...","[ABS, Adaptive Cruise Control, Blind spot moni...","[ABS, Blind spot monitor, Driver-side airbag, ...","[ABS, Blind spot monitor, Daytime running ligh..."
description,"[\n, Sicherheit:, , Deaktivierung für Beifahr...",[\nLangstreckenfahrzeug daher die hohe Kilomet...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...","[\nAudi A1: , - 1e eigenaar , - Perfecte staat...","[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",[\nSichern Sie sich diesen Audi A1 1.6 TDI Spo...,"[\nREDUZIERT !!!, MwSt. ausweisbar, Nettopreis...","[\n, Ausstattungspakete:, Ausstattungspaket: ...",[\nAuto in ottime condizioni. Unico proprietar...,"[\nClim automatique,Ecran multifonction couleu...",...,"[\nHallo!, Das Beratungsteam der Fa. Sonnleitn...","[\n, Warum ist dieses Auto das Richtige für mi...","[\n, Komfort:, , abgedunkelte Scheiben im Fon...",[\nVettura visionabile nella sede in Via Roma ...,"[\nFahrzeug-Nr.: NW9766., Ausstattungslinie/ -...",[\nVettura visionabile nella sede in Via Roma ...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...","[\n, Getriebe:, Automatik, Technik:, Bordcom...","[\nDEK:[2691331], Renault Espace Blue dCi 200C...","[\n, Sicherheit Airbags:, , Seitenairbag, , ..."
Emission Label,NaN,[\n4 (Green)\n],[\n4 (Green)\n],NaN,NaN,[\n4 (Green)\n],NaN,NaN,NaN,NaN,...,NaN,[\n4 (Green)\n],[\n4 (Green)\n],NaN,[\n4 (Green)\n],NaN,NaN,NaN,NaN,[\n4 (Green)\n]
Gears,NaN,[\n7\n],NaN,[\n6\n],NaN,NaN,NaN,[\n7\n],[\n7\n],[\n7\n],...,[\n7\n],[\n7\n],NaN,[\n6\n],NaN,[\n6\n],[\n7\n],[\n6\n],[\n6\n],NaN
Country version,NaN,NaN,NaN,NaN,[\nGermany\n],[\nGermany\n],[\nGermany\n],NaN,NaN,NaN,...,[\nAustria\n],NaN,[\nGermany\n],NaN,NaN,NaN,[\nGermany\n],[\nAustria\n],NaN,[\nGermany\n]
Electricity consumption,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last Service Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Other Fuel Types,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[[], [], []]",NaN,NaN,NaN
Availability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,\nin 5 days from ordering\n,\nin 120 days from ordering\n,NaN,NaN
Last Timing Belt Service Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Available from,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df["\nComfort & Convenience\n"].isnull().sum()

920

In [31]:
df["\nComfort & Convenience\n"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[Air conditioning, Electrical side mirrors, Hill Holder, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                      216
[Air conditioning, Electrical side mirrors, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                                   134
[Air conditioning, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            130
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                                                                                                                                         105
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                                                                                                                                                                                  92
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
[Air conditioning, Cruise control, Electrical side mirrors, Multi-function steering wheel, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Start-stop system]                                                                                                                                                                                                                                                                                                   1
[Air conditioning, Armrest, Cruise control, Electrical side mirrors, Heated steering wheel, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Park Distance Control, Parking assist system camera, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Sunroof, Tinted windows]                                                                                                                                                 1
[Air conditioning, Armrest, Cruise control, Hill Holder, Leather steering wheel, Multi-function steering wheel, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Power windows]                                                                                                                                                                                                                                                                                                 1
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Multi-function steering wheel, Power windows, Rain sensor, Start-stop system, Tinted windows]                                                                                                                                                                                                                                                                                                          1
[Air conditioning, Automatic climate control, Cruise control, Electrically heated windshield, Electrical side mirrors, Electric tailgate, Heads-up display, Heated steering wheel, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Lumbar support, Navigation system, Park Distance Control, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Sunroof]      1
Name: \nComfort & Convenience\n, Length: 6198, dtype: int64

In [32]:
df["\nEntertainment & Media\n"].isnull().sum()

1374

In [33]:
df["\nEntertainment & Media\n"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[Bluetooth, Hands-free equipment, On-board computer, Radio, USB]                         1282
[Bluetooth, Hands-free equipment, MP3, On-board computer, Radio, USB]                     982
[Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB]          783
[On-board computer, Radio]                                                                487
[Radio]                                                                                   477
                                                                                         ...
[Bluetooth, CD player, MP3]                                                                 1
[CD player, USB]                                                                            1
[Bluetooth, CD player, Digital radio, Radio, USB]                                           1
[Bluetooth, CD player, Digital radio, MP3, On-board computer, Radio, Television, USB]       1
[Hands-free equipment, On-board computer, Radio, Sound system]                              1
Name: \nEntertainment & Media\n, Length: 346, dtype: int64

In [36]:
df["\nExtras\n"].isnull().sum()

2962

In [35]:
df["\nExtras\n"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[Alloy wheels]                                                                                                     3245
[Alloy wheels, Touch screen]                                                                                        697
[Alloy wheels, Voice Control]                                                                                       577
[Alloy wheels, Touch screen, Voice Control]                                                                         541
[Alloy wheels, Roof rack]                                                                                           385
                                                                                                                   ...
[Alloy wheels, Catalytic Converter, Shift paddles, Sport package, Sport seats, Sport suspension, Voice Control]       1
[Alloy wheels, Catalytic Converter, Roof rack, Sport package, Sport seats, Trailer hitch]                             1
[Alloy wheels, Catalytic Converter, Ski bag, Sport package, Voice Control]                                            1
[Catalytic Converter, Roof rack, Sport seats, Sport suspension]                                                       1
[Alloy wheels, Shift paddles, Ski bag, Sport seats, Sport suspension, Touch screen, Voice Control]                    1
Name: \nExtras\n, Length: 659, dtype: int64

In [37]:
df["\nSafety & Security\n"].isnull().sum()

982

In [38]:
df["\nSafety & Security\n"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                                                           538
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                                                                       480
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]                                                                                                                                     275
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                               272
[ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                                           228
                                                                                                                                                                                                                                                                                                                                                                                    ...
[ABS, Central door lock, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag]                                                                                                                                                                                                                                                        1
[ABS, Adaptive Cruise Control, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Emergency brake assistant, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control]                                                                                                     1
[ABS, Adaptive Cruise Control, Alarm system, Central door lock, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Lane departure warning system, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]                                                 1
[ABS, Adaptive Cruise Control, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Power steering, Tire pressure monitoring system, Traction control]                                                                                                                                                        1
[ABS, Adaptive Cruise Control, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Emergency brake assistant, Fog lights, Immobilizer, Isofix, Lane departure warning system, LED Daytime Running Lights, LED Headlights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traffic sign recognition]      1
Name: \nSafety & Security\n, Length: 4443, dtype: int64

In [39]:
df["description"].isnull().sum()

0

In [40]:
df["description"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        636
[\n, \n]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   30
[\n, Fahrzeugbeschreibung,  Sichern Sie sich diesen Renault Clio 1.6 TCE Energy Sport Trophy zum Top-Preis inklusive dem , AUTOHERO-RUNDUM-SORGLOS-PAKET,  , Infos:,  1.Hand, deutsche Auslieferung, Unfallfrei, scheckheftgepflegt,  , Highlights,  , Audio-Navigationssystem R-Link Evolution mit Touchscreen und Carminat TomTom,  , Sportsitze ,  , Sportfahrwerk,  , Scheinwerfer Full-LED , Komfort,  , Geschwindigkeits-Regelanlage (Tempomat) ,  , Klimaanlage,  , Einparkhilfe hinten,  , Multifunktionslenkrad (Sport/Leder) mit Schaltwippen/-tasten ,  , Fensterheber elektr. mit Impulsgeber links/rechts vorn,  , Zentralverriegelung / Startanlage Handsfree Entry & Drive ,  , Berganfahr-Assistent (HSA) , Multimedia,  , Audiosystem: Radio R & GO (Bluetooth, DAB-Tuner),  , Bordcomputer,  , Freisprecheinrichtung Bluetooth ,  , USB-Anschluss inkl. AUX-IN-Anschluss (Plug & Music) , Licht und Sicht,  , Außenspiegel elektr. verstell- und heizbar ,  , Licht- und Regensensor ,  , Tagfahrlicht LED ,  , Nebelscheinwerfer LED ,  , Coming-Home-Lichtfunktion ,  , Heckleuchten LED , Sicherheit,  , Isofix-Aufnahmen für Kindersitz ,  , Seitenairbag vorn,  , Wegfahrsperre,  , Differentialsperre,  , Bremsassistent ,  , Elektron. Stabilitäts-Programm (ESP),  , Anti-Blockier-System (ABS),  , Anti-Submarining-Airbag im Fond,  , Airbag Fahrer-/Beifahrerseite ,  , Differentialsperre ,  , Reifendruck-Kontrollsystem ,  , Untersteuerungskontrolle (USC) ,  , Antischlupfregelung (ASR) , Weiteres,  , Start/Stop-Anlage ,  , Servolenkung geschwindigkeitsabhängig,  , R.S. Drive (Fahrmodusschalter) ,  , Gepäckraumabdeckung / Rollo ,  , Heckdiffusor ,  , LM-Felgen ,  , Heckspoiler (Renault Sport) ,  , Pedale Aluminium ,  , Energierückgewinnung (Energy Smart Management) , ...]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              27
[\nPosibilidad de prueba del vehículo hasta 5 días. Consultar condiciones. PVP para particulares. Varias unidades y colores disponibles. Precios publicados para vehículos industriales (furgonetas) válidos para compradores autónomos o empresas, consultar condiciones para particulares. Las imágenes y kilómetros pueden no corresponder con el modelo anunciado. Para confirmar póngase en contacto con nuestro departamento comercial. Consulta las excepcionales condiciones de financiación que tenemos disponibles. Precio de venta final IVA y gastos de transferencia incluidos. Horario de atención al cliente: Lunes a Viernes de 09:00 a 18:00.\n]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          27
[\nSichern Sie sich diesen RENAULT CLIO 1.2 LIMITED zum Top-Preis inklusive dem, AUTOHERO-RUNDUM-SORGLOS-PAKET,  , Infos:,  2.Hand, mindestens 12 Monate gültige HU und AU, deutsche Ausführung, unfallfrei ,  , Highlights,  , Audio-Navigationssystem mit Touchscreen-Farbdisplay, Komfort,  , Klimaanlage ,  , Multifunktionslenkrad in Leder ,  , Berganfahr-Assistent (HSA),  , Fensterheber elektrisch vorn ,  , Geschwindigkeits-Regelanlage (Tempomat) ,  , Heckscheibe heizbar ,  , Sitz vorn links höhenverstellbar,  , Sitz vorn rechts umklappbar ,  , Stau-/Ablagefach im Laderaumboden ,  , Zentralverriegelung mit Fernbedienung , Multimedia,  , Radio R&GO,  , Bluetooth Freisprechanlage ,  , USB-/AUX-Schnittstelle ,  , Bordcomputer,  , Licht und Sicht,  , Tagfahrlicht LED ,  , Außenspiegel elektrisch verstell- und heizbar, Sicherheit,  , Airbag für Fahrer und Beifahrer,  , Beifahrerairbag deaktivierbar ,  , Seitenairbags vorn ,  , Kopfairbagsystem,  , Anti-Blockier-System (ABS),  , Elektronische Bremskraftverteilung ,  , Elektronische Stabilitäts-Programm (ESP) ,  , Reifen-Reparaturkit ,  , Reifendruck-Kontrollsystem ,  , Untersteuerungskontrolle (USC) ,  , ISOFIX Kindersitzverankerung , Weiteres,  , Dachreling silber ,  , Look-Paket Chrom (außen) ,  , Look-Paket Grau (innen) ,  , R&GO-Paket ,  , Style-Paket ,  Ihr , AUTOHERO-RUNDUM-SORGLOS-PAKET,  beinhaltet:, Kostenlose Lieferung in Ihre Nähe, Optische & technische Aufbereitung, Mindestens 12 Monate gültige HU und AU, 1-Jahr-Premium-Garantie, Zulassung inklusive , 14-Tage-Rückgaberecht, Markenunabhängige Inzahlungnahme , Individuelle Finanzierungen zu fairen Konditionen,  , HIER GEHT ES ZUR 360° - ANSICHT DES FAHRZEUGES:, :, https://www.autohero.com/de/renault-clio-1-2-limited/id/30f99516-8785-47e7-a4a3-6cdac4d8e633/,  , Haftungsausschluss, :, Für Angaben vom Verkäufer, des Herstellers oder von Datenbankabfragen übernimmt Autohero keine Haftung. Änderungen, Zwischenverkauf und Irrtümer sind vorbehalten.\n]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                27
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ...
[\nPratica 67374, Airbag fullsize per conducente e passeggero, Alzacristalli elettrici ant. e post. con funzione attivaz. a pressione, Assetto dinamico, Audi drive select, Inserti in micrometallic argento, Kit riparazione pneumatici, Pacchetto di navigazione, Piano di copertura del vano bagagli estraibile, Presa AUX-IN, Proiettori allo Xenon Plus con reg. aut. prof. fari, Lavafari, Rivestimenti dei sedili in tessuto, Serbatoio AdBlue, Sistema controllo pressione pneumatici, Sistema di ancoraggio ISOFIX e 3° punto di ancoraggio Top Tether sui sedili post. laterali, Sistema di informazioni per il conducente con display monocromatico, Tappetini anteriori e posteriori, Versione Business, Volante sportivo multifunzionale in pelle 3 razze, ABS, EBV (Ripartitore elettronico della forza frenante), Airbag laterali anteriori integrati negli schienali dei sedili, Airbag per la testa, Airbag per le ginocchia (lato conducente), Appoggiatesta anteriori (2) e posteriori (3) regolabili, Radio MMI plus, Interfaccia Bluetooth, Appoggiabraccia centrale anteriore, Cambio manuale, Cerchi in lega 7 J x 16" a 5 razze a stella, Chiusura centralizzata con telecomando, Regolatore di velocità, ESC - Sistema elettronico di controllo della stabilizzazione con bloccaggio trasversale elettronico, ASR - Dispositivo di controllo della trazione, EDS (Dispositivo antislittamento in partenza), Filtro anti particolato, Cinture di sicurezza con pretensionatore, Specchietti retrovisivi esterni riscaldabili e ripiegabili elettricamente, Schienale del sedile posteriore ribaltabile (divisibile in rapporto 40:60 o ribaltabile completam.), Sistema di ausilio al parcheggio posteriore, Servosterzo elettromeccanico, Tergilunotto\n]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1

In [41]:
df["Emission Label"].isnull().sum()

11934

In [42]:
df["Emission Label"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n4 (Green)\n]         3553
[\n1 (No sticker)\n]     381
[[], [], []]              40
[\n5 (Blue)\n]             8
[\n3 (Yellow)\n]           2
[\n2 (Red)\n]              1
Name: Emission Label, dtype: int64

In [44]:
df["Gears"].isnull().sum()

4712

In [46]:
df["Gears"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n6\n]     5822
[\n5\n]     3239
[\n7\n]     1908
[\n8\n]      224
[\n9\n]        6
[\n1\n]        2
[\n3\n]        2
[\n4\n]        2
[\n2\n]        1
[\n50\n]       1
Name: Gears, dtype: int64

In [48]:
df["Country version"].isnull().sum()

8333

In [49]:
df["Country version"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\nGermany\n]           4502
[\nItaly\n]             1038
[\nEuropean Union\n]     507
[\nNetherlands\n]        464
[\nSpain\n]              325
[\nBelgium\n]            314
[\nAustria\n]            208
[\nCzech Republic\n]      52
[\nPoland\n]              49
[\nFrance\n]              38
[\nDenmark\n]             33
[\nHungary\n]             28
[\nJapan\n]                8
[\nSlovakia\n]             4
[\nCroatia\n]              4
[\nSweden\n]               3
[\nRomania\n]              2
[\nBulgaria\n]             2
[\nLuxembourg\n]           1
[\nSwitzerland\n]          1
[\nSlovenia\n]             1
[\nEgypt\n]                1
[\nSerbia\n]               1
Name: Country version, dtype: int64

In [50]:
df["Electricity consumption"].isnull().sum()

15782

In [51]:
df["Electricity consumption"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n0 kWh/100 km (comb)\n]    137
Name: Electricity consumption, dtype: int64

In [52]:
df["Last Service Date"].isnull().sum()

15353

In [53]:
df["Last Service Date"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n02/2019\n, \nEuro 6\n]                 23
[\n05/2019\n, \nEuro 6\n]                 16
[\n01/2018\n, \n118 g CO2/km (comb)\n]    15
[\n03/2019\n, \nEuro 6\n]                 15
[\n06/2019\n, \nEuro 6\n]                 13
                                          ..
[\n01/2017\n, \n95 g CO2/km (comb)\n]      1
[\n06/2019\n, \n87 g CO2/km (comb)\n]      1
[\n10/2018\n, \n100 g CO2/km (comb)\n]     1
[\n02/2018\n, \n97 g CO2/km (comb)\n]      1
[\n03/2019\n, \n120 g CO2/km (comb)\n]     1
Name: Last Service Date, Length: 266, dtype: int64

In [54]:
df["Other Fuel Types"].isnull().sum()

15039

In [55]:
df["Other Fuel Types"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[[], [], []]    880
Name: Other Fuel Types, dtype: int64

In [56]:
df["Availability"].isnull().sum()

15284

In [57]:
df["Availability"].value_counts()

\nin 90 days from ordering\n     196
\nin 120 days from ordering\n    182
\nin 1 day from ordering\n        51
\nin 5 days from ordering\n       35
\nin 3 days from ordering\n       35
\nin 180 days from ordering\n     24
\nin 14 days from ordering\n      24
\nin 7 days from ordering\n       20
\nin 150 days from ordering\n     18
\nin 2 days from ordering\n       16
\nin 60 days from ordering\n      13
\nin 42 days from ordering\n      10
\nin 21 days from ordering\n       8
\nin 4 days from ordering\n        2
\nin 6 days from ordering\n        1
Name: Availability, dtype: int64

In [58]:
df["Last Timing Belt Service Date"].isnull().sum()

15903

In [59]:
df["Last Timing Belt Service Date"].value_counts()

TypeError: ignored

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[\n04/2016\n]                2
[\n12/1900\n]                1
[\n07/2018\n]                1
[\n01/1900\n]                1
[\n05/2019\n]                1
[\n09/2018\n]                1
[\n05/2018\n, \nEuro 6\n]    1
[\n06/2017\n]                1
[\n01/2019\n]                1
[\n02/2019\n]                1
[\n02/2018\n]                1
[\n06/2019\n]                1
[\n01/2018\n]                1
[\n04/2019\n]                1
[\n01/1970\n]                1
Name: Last Timing Belt Service Date, dtype: int64

In [60]:
df["Available from"].isnull().sum()

15647

In [61]:
df["Available from"].value_counts()

\n31/08/19\n    98
\n30/07/19\n    25
\n15/08/19\n    24
\n16/09/19\n    14
\n29/06/19\n    12
\n01/07/19\n    11
\n28/06/19\n    10
\n19/08/19\n     7
\n10/09/19\n     6
\n26/06/19\n     5
\n27/06/19\n     5
\n10/11/19\n     5
\n08/07/19\n     4
\n25/10/19\n     3
\n15/07/19\n     3
\n01/08/19\n     3
\n04/07/19\n     2
\n05/08/19\n     2
\n24/08/19\n     2
\n16/07/19\n     2
\n20/07/19\n     2
\n05/07/19\n     2
\n30/06/19\n     2
\n30/09/19\n     1
\n31/10/19\n     1
\n27/07/19\n     1
\n02/07/19\n     1
\n10/07/19\n     1
\n19/07/19\n     1
\n24/07/19\n     1
\n29/07/19\n     1
\n29/09/19\n     1
\n18/08/19\n     1
\n14/09/19\n     1
\n18/07/19\n     1
\n16/08/19\n     1
\n24/09/19\n     1
\n17/08/19\n     1
\n10/10/19\n     1
\n06/12/19\n     1
\n03/12/19\n     1
\n05/12/19\n     1
\n11/08/19\n     1
\n10/12/19\n     1
\n01/09/19\n     1
\n03/08/19\n     1
Name: Available from, dtype: int64

## Import Libraries and Data

In [ ]:
df_dummied.to_csv("final_scout_dummy.csv", index=False)

In [ ]:
df.to_csv("final_scout_not_dummy.csv", index=False)